### ISSUE TITLE
Errors After the upgrade 

### ISSUE THREAD

**Issue by junoonis** [taniman/profit-trailer#1029]
Below are the list of errors I am gettign after upgrading to latest PT.

`2018-02-07 19:13:19 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:13:26 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:13:33 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:13:40 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:13:47 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:13:52 ERROR ProfitTrailerService - Occured in TH, handled result exception The CacheManager has been shut down. It can no longer be used.
2018-02-07 19:13:52 INFO ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see
2018-02-07 19:13:52 ERROR GenericStrategyRunner - An error occured
2018-02-07 19:13:52 ERROR GenericStrategyRunner - An error occured
2018-02-07 19:13:52 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: The ticker Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:67) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:537) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:503) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$38612ccc.getTickers(<generated>) ~[classes!/:1.2.6.12]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:63) ~[classes!/:1.2.6.12]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-02-07 19:14:23 INFO Util - Detected configuration changes
2018-02-07 19:14:23 INFO ProfitTrailerService - Normal Heartbeat
2018-02-07 19:14:23 INFO ProfitTrailerService - DCA Heartbeat
2018-02-07 19:14:25 INFO ProfitTrailerService - Cache Heartbeat
2018-02-07 19:15:02 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:15:09 ERROR DCAStrategyRunner - An error occured
2018-02-07 19:17:39 INFO Util - Detected configuration changes
2018-02-07 19:17:40 INFO ProfitTrailerService - Normal Heartbeat
2018-02-07 19:17:40 INFO ProfitTrailerService - DCA Heartbeat
2018-02-07 19:17:40 INFO ProfitTrailerService - Cache Heartbeat
2018-02-07 19:24:59 INFO ProfitTrailerService - SOM is active for BCPTBTC. -- Manually set in PAIRS.properties
2018-02-07 19:25:05 ERROR DCAStrategyRunner - An error occured
nl.komtek.pt.utils.b: ERROR: -2010, Account has insufficient balance for requested action.
	at nl.komtek.pt.services.ProfitTrailerService.d(ProfitTrailerService.java:902) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:844) ~[classes!/:1.2.6.15]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.b(ProfitTrailerService.java:844) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:807) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.15]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6b0894d2.a(<generated>) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:206) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:140) [classes!/:1.2.6.15]
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by mather21** [comment]
just updated the jar file now i get this error : 0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:56 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.util.net.SocketBufferHandler
0|profit-t |    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
0|profit-t |    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
0|profit-t |    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
0|profit-t |    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
0|profit-t |    ... 3 more
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:56 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:56 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:56 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:57 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:57 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:57 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:58 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:58 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: Feb 08, 2018 12:53:58 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:53 +00:00: 2018-02-08 00:53:59 INFO ProfitTrailerService - Normal Heartbeat
0|profit-t | 2018-02-08 00:53 +00:00: 2018-02-08 00:53:59 INFO ProfitTrailerService - Cache Heartbeat
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:03 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:03 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:04 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:04 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:04 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:05 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:05 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:05 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:06 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:06 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:08 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: 2018-02-08 00:54:19 INFO ProfitTrailerService - DCA Heartbeat
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:34 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:35 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:35 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:35 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:36 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:36 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:36 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:37 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:37 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:37 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)
0|profit-t | 2018-02-08 00:54 +00:00: Feb 08, 2018 12:54:42 AM org.apache.tomcat.util.net.NioEndpoint setSocketOptions
0|profit-t | SEVERE:
0|profit-t | java.lang.NoClassDefFoundError: org/apache/tomcat/util/net/SocketBufferHandler
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:375)
0|profit-t |    at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:473)
0|profit-t |    at java.lang.Thread.run(Thread.java:748)

**Comment by junoonis** [comment]
For time being, I reverted to older Jar, lets see how it runs

**Comment by cristianserban** [comment]
if it is on binance https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension
