### ISSUE TITLE
Not receiving telegram notifications from PT.

### ISSUE THREAD

**Issue by mikeyshann** [taniman/profit-trailer#1094]
for some reason, my Bot has stopped sending me notifications for buys and sells. I run PT Feeder and receive messages from it but I am not receiving any messages from the Profit Trailer. I’m 100% sure that my ChatID and chat token numbers are correct. Anyone else have this issue or any way I can troubleshoot this and find a fix? Thanks I’m advance! Especially the Devs. You guys are awesome.

**Comment by mikeyshann** [comment]
I’m running the latest PT too. I also had the problem while running the last 2 previous releases. Just stopped sending for some reason.

**Comment by ngreiner** [comment]
I'm also not getting (some) Telegram Buy/Sell messages. I do see a stack trace in some cases (see below). Not sure if its related but there were some price mismatch issues very near to the Telegram errors.
------------------------------------------------------------------
2018-02-14 05:03:42 INFO AverageCalculator - ENJBTC - Price mismatch of 99.581776 %. Let me recalculate
2018-02-14 05:03:42 INFO AverageCalculator - ENJBTC - Price mismatch of 213.105, Let me recalculate...
2018-02-14 05:03:43 ERROR TelegramService - Error sending your telegram message {}
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230) ~[okio-1.13.0.jar!/:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[okio-1.13.0.jar!/:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[okio-1.13.0.jar!/:?]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) ~[okio-1.13.0.jar!/:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) ~[okio-1.13.0.jar!/:?]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) ~[okio-1.13.0.jar!/:?]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar!/:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) [okhttp-3.8.1.jar!/:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.1.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_161]
	at java.net.SocketInputStream.socketRead(Unknown Source) ~[?:1.8.0_161]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_161]
	at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_161]
	at sun.security.ssl.InputRecord.readFully(Unknown Source) ~[?:1.8.0_161]
	at sun.security.ssl.InputRecord.read(Unknown Source) ~[?:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_161]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source) ~[?:1.8.0_161]
	at sun.security.ssl.AppInputStream.read(Unknown Source) ~[?:1.8.0_161]
	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar!/:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar!/:?]
	... 23 more

**Comment by mikeyshann** [comment]
I am not receiving any errors. At one point in the previous release, I set up BTC rise and drop triggers. When I did this, my bot would send me hundreds of notifications when a trigger was met. I restarted a fresh setup and now I don't get any messages at all. Even with the latest release, I set up an new install and still don't receive any messages.
