### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by iamsnehal** [taniman/profit-trailer#1220]
Hi There,
We are getting the below error on bot. We had feeder also installed.

2018-02-22 21:45:11 ERROR DCAStrategyRunner - An error occured
java.lang.IllegalStateException: The completeBalances Cache is not alive (STATUS_SHUTDOWN)
        at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
        at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
        at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
        at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:74) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e6f48e27.getCompleteBalances(<generated>) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.a(StrategyRunnerHelper.java:58) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.b(StrategyRunnerHelper.java:116) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:683) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.18]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e6f48e27.a(<generated>) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:354) ~[classes!/:1.2.6.18]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:144) [classes!/:1.2.6.18]
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by iamsnehal** [comment]
Can  we have beta version, if possible? We are still not trading with big value yet, so can help in testing, and can provide early feedback/issue, in beta.
