### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by richardsizemore** [taniman/profit-trailer#1232]
2018-02-23 12:23:21 INFO ProfitTrailerService - Cache Heartbeat
2018-02-23 12:23:26 INFO ProfitTrailerService - DCA Heartbeat
2018-02-23 12:23:31 INFO ProfitTrailerService - Normal Heartbeat
2018-02-23 12:24:00 INFO DCAStrategyRunner - You are not allowed to buy LTCUSDT. Buy will exceed min buy balance 121.17316992. BAL: 23.31446003 - AVGC: 46.3230768
2018-02-23 12:26:55 ERROR DCAStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_161]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_161]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_161]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_161]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_161]
at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_161]
at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:1.2.6.19]
at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:39) ~[classes!/:1.2.6.19]
at nl.komtek.pt.bot.strategy.helper.a.a(BBHelper.java:30) ~[classes!/:1.2.6.19]
at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:404) ~[classes!/:1.2.6.19]
at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:232) ~[classes!/:1.2.6.19]
at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:145) [classes!/:1.2.6.19]
at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-02-23 12:29:03 INFO DCAStrategyRunner - You are not allowed to buy LTCUSDT. Buy will exceed min buy balance 121.17316992. BAL: 23.31446003 - AVGC: 46.3230768
2018-02-23 12:33:24 INFO ProfitTrailerService - Cache Heartbeat
2018-02-23 12:33:29 INFO ProfitTrailerService - DCA Heartbeat
2018-02-23 12:33:35 INFO ProfitTrailerService - Normal Heartbeat

**Comment by orty87** [comment]
Same thing for me on rpi3. Prevous version worked

**Comment by taniman** [comment]
This message does not break the bot. It can be ignored fro now. Will be fixed in future release
