### ISSUE TITLE
Java Exception Windows 2012 Server

### ISSUE THREAD

**Issue by smartdevs** [taniman/profit-trailer#1281]
2018-02-26 16:33:33 ERROR NormalStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_162]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_162]
        at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:1.2.6.19]
        at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:39) ~[classes!/:1.2.6.19]
        at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.b(StrategyCalculations.java:101) ~[classes!/:1.2.6.19]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.a(NormalStrategyRunner.java:206) ~[classes!/:1.2.6.19]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:161) [classes!/:1.2.6.19]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]

**Comment by cristianserban** [comment]
binance ?

**Comment by smartdevs** [comment]
yes

**Comment by smartdevs** [comment]
Version 19

**Comment by YoJeff** [comment]
I'd try an upgrade to the latest version.   Let me know.
