### ISSUE TITLE
2018-03-03 10:52:57 ERROR GainStrategyRunner - An error occured com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

### ISSUE THREAD

**Issue by juato4** [taniman/profit-trailer#1343]
2018-03-03 10:52:57 ERROR GainStrategyRunner - An error occured
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar!/:?]
        at com.cf.data.map.binance.BinanceDataMapper.mapExchangeInfo(BinanceDataMapper.java:119) ~[x-client-1.2.9.jar!/:?]
        at com.cf.data.map.generic.DataMapper.mapExchangeInfo(DataMapper.java:325) ~[x-client-1.2.9.jar!/:?]
        at nl.komtek.pt.services.ProfitTrailerService.getExchangeInfo(ProfitTrailerService.java:877) ~[classes!/:1.2.6.20]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.20]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$8736e2ac.getExchangeInfo(<generated>) ~[classes!/:1.2.6.20]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.20]
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-03-03 10:52:57 INFO DCAStrategyRunner - Cooling down for 1 minute
2018-03-03 10:53:57 INFO DCAStrategyRunner - We got temp banned. Waiting 5 minutes

**Comment by juato4** [comment]
2018-03-03 12:58:58 INFO NormalStrategyRunner - Cooling down for 1 minute
2018-03-03 12:59:58 INFO NormalStrategyRunner - We got temp banned. Waiting 5 minutes
2018-03-03 13:05:09 INFO ProfitTrailerService - Normal Heartbeat
2018-03-03 13:05:30 INFO ProfitTrailerService - DCA Heartbeat
2018-03-03 13:05:40 INFO NormalStrategyRunner - You are not allowed to buy ENGETH. Buy will exceed min buy balance 7.33818336. BAL: 7.29717351 - MC: 0.0312
2018-03-03 13:05:45 INFO ProfitTrailerService - Cache Heartbeat
2018-03-03 13:05:57 ERROR GenericStrategyRunner - An error occured
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar!/:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar!/:?]
        at com.cf.data.map.binance.BinanceDataMapper.mapExchangeInfo(BinanceDataMapper.java:119) ~[x-client-1.2.9.jar!/:?]
        at com.cf.data.map.generic.DataMapper.mapExchangeInfo(DataMapper.java:325) ~[x-client-1.2.9.jar!/:?]
        at nl.komtek.pt.services.ProfitTrailerService.getExchangeInfo(ProfitTrailerService.java:877) ~[classes!/:1.2.6.20]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.20]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$8736e2ac.getExchangeInfo(<generated>) ~[classes!/:1.2.6.20]
        at nl.komtek.pt.strategyrunner.GenericStrategyRunner.a(GenericStrategyRunner.java:306) [classes!/:1.2.6.20]
        at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:87) [classes!/:1.2.6.20]
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-03-03 13:05:57 INFO GenericStrategyRunner - Cooling down for 1 minute
2018-03-03 13:07:01 INFO NormalStrategyRunner - You are not allowed to buy AMBETH. Buy will exceed min buy balance 7.33669066. BAL: 7.29717351 - MC: 0.0312

**Comment by taniman** [comment]
This error is jsut saying that the data we got from the exchange is not what we expected.

are you running multiple binance instances? Seems like it. cause you are being banned

**Comment by juato4** [comment]
No i am not running múltiple binance instantes.

Just only 1 PT and moonbot

Enviado desde mi iPhone

**Comment by taniman** [comment]
please contact support on discord to look further into this. I am not sure if moonbot connects to binance. but if so. this may be causing connection limit problem
