### ISSUE TITLE
DCA error

### ISSUE THREAD

**Issue by DragonBtc93** [taniman/profit-trailer#1407]
2018-03-10 16:11:07 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_151]
        at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:181) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:150) [classes!/:1.2.6.23]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Mar 10, 2018 4:11:09 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-03-10 16:11:17 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_151]
        at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:181) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:150) [classes!/:1.2.6.23]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-03-10 16:11:27 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_151]
        at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:181) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:150) [classes!/:1.2.6.23]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

My Pairs
MARKET = BTC

#If you turn on trading the bot will try to sell ANY coin you already own
ALL_trading_enabled = true
ALL_enabled_pairs = ALL
ALL_max_cost = 0.0018
ALL_min_buy_balance = 0
ALL_min_buy_volume = 500
ALL_min_buy_price = 0.0001
ALL_max_trading_pairs = 10
#ALL_max_buy_spread = 1
ALL_buy_strategy = LOWBB
ALL_buy_value = -15
ALL_trailing_buy = 0.093
#ALL_buy_strategy = EMACROSS
#ALL_buy_value = 0.20
#ALL_trailing_buy = 0
#ALL_buy_value_limit = 3 
ALL_sell_strategy =  HIGHBB
ALL_sell_value = 15
ALL_min_profit = 0.85
ALL_trailing_profit = 0.093
#ALL_sell_strategy = GAIN
#ALL_sell_value = 1
#ALL_trailing_profit = 0.5
#All_stop_loss_trigger = -2
ALL_stop_loss_timeout = 10
ALL_panic_sell_enabled = false
ALL_DCA_enabled = 1.49
ALL_sell_only_mode = false
ALL_pending_order_wait_time = 0
ALL_combined_cancel_pending_trigger = 0
ALL_hidden_pairs = BNBBTC
BNBBTC_trading_enabled =  false
#BTCUSDT_DCA_enabled = true

My DCA
enabled = true
max_cost = 0
max_buy_times = 5
max_buy_spread = 1
#min_buy_balance = 0.06
rebuy_timeout = 30
buy_available_volume_trigger = 100
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -1.5
buy_trigger_2 = -2.5
buy_trigger_3 = -4.5
buy_trigger_4 = -7.5
buy_trigger_5 = -10.5
trailing_buy = 0.195
ALL_sell_strategy =  HIGHBB
ALL_sell_value = 15
ALL_min_profit = 0.85
ALL_trailing_profit = 0.093
pending_order_wait_time = 0
ignore_sell_only_mode = true
min_buy_balance = 0
order_wait_time = 0

**Comment by DragonBtc93** [comment]
Tried reinstalling java now it gives this when I have dca on
2018-03-10 16:58:06 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_161]
        at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:181) ~[classes!/:1.2.6.23]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:150) [classes!/:1.2.6.23]
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by DragonBtc93** [comment]
Ok figured out it is the HIGHBB sell in the DCA. If I put it on gain it works but why?

**Comment by taniman** [comment]
You did not put it correctly as the errors were because buy_strategy or sell_strategy was missing

**Comment by DragonBtc93** [comment]
I see what I did now. Thank you
