### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by fixerfax** [taniman/profit-trailer#1484]
Just started today. Hadn't changed any settings. Please advise:

2018-03-21 22:31:23 ERROR NormalStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
        at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.25]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.t(StrategyRunnerHelper.java:441) ~[classes!/:1.2.6.25]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:102) [classes!/:1.2.6.25]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by SgtBatten** [comment]
You have a missing trade strategy. This is not a bug. Please come to discord for further support.

**Comment by anishpillaimca** [comment]
I am getting the same error. Which trade strategy was missing?
