### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by mydonose16** [taniman/profit-trailer#1500]
ERROR ProfitTrailerService - Occured in TH, handled result exception The CacheManager has been shut down. It can no longer be used.
2018-03-25 23:55:31 INFO ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see
2018-03-25 23:55:31 ERROR GenericStrategyRunner - An error occured
java.lang.IllegalStateException: The exchangeInfo Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:67) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:537) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:503) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$2d540de3.getExchangeInfo(<generated>) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.a(GenericStrategyRunner.java:310) [classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:93) [classes!/:1.2.6.25]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-03-25 23:55:31 ERROR GenericStrategyRunner - An error occured
java.lang.IllegalStateException: The openOrders Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:74) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$2d540de3.getOpenOrders(<generated>) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.a(GenericStrategyRunner.java:235) [classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:94) [classes!/:1.2.6.25]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-03-25 23:55:31 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: The ticker Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:67) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:71) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:537) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:503) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:389) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$2d540de3.getTickers(<generated>) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:74) ~[classes!/:1.2.6.25]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-03-25 23:56:13 INFO ProfitTrailerService - LOADING REQUIRED DATA....
2018-03-25 23:56:26 INFO Application - PT Version: 1.2.6.25
2018-03-25 23:56:26 INFO Application - Java Version: 1.8.0_161
2018-03-25 23:56:41 INFO Util - Detected configuration changes

**Comment by mydonose16** [comment]
by the way my bot stop buying after 10-16 hours later.

**Comment by YoJeff** [comment]
Go through support first.
https://wiki.profittrailer.com/doku.php
