### ISSUE TITLE
ERROR GainStrategyRunner: NullPointerException

### ISSUE THREAD

**Issue by buschjost** [taniman/profit-trailer#1575]
I am running v2  in TESTMODE at the moment. First it ran good, but then I got this Exception:

```
2018-04-21 20:28:16 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:2.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_162]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:246) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:47) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.a(StrategyCalculations.java:627) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.a(GainStrategyRunner.java:170) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:107) [classes!/:2.0]
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-04-21 20:28:22 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:2.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_162]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:246) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:47) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.a(StrategyCalculations.java:627) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.a(GainStrategyRunner.java:170) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:107) [classes!/:2.0]
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-04-21 20:28:27 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:2.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_162]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:246) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:47) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.a(StrategyCalculations.java:627) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.a(GainStrategyRunner.java:170) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:107) [classes!/:2.0]
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-04-21 20:28:32 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:245) ~[classes!/:2.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_162]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_162]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:246) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.c.a(TimeSeriesHelper.java:47) ~[classes!/:2.0]
	at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.a(StrategyCalculations.java:627) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.a(GainStrategyRunner.java:170) ~[classes!/:2.0]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:107) [classes!/:2.0]
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-04-21 20:28:38 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:28:44 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:28:49 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:28:54 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:29:00 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:29:05 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:29:10 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:29:16 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null

....

2018-04-21 20:37:48 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2018-04-21 20:39:09 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
^C^C^C2018-04-21 20:39:20 INFO TelegramService - TEST MODE - Telegram message sent - BINANCE BTC - ProfitTrailer Bot shutting down!
2018-04-21 20:39:20 INFO DiscordService - Discord message sent - BINANCE BTC - ProfitTrailer Bot v2.0 shutting down!
^C^C^C^C^C^C2018-04-21 20:41:12,509 Thread-13 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

Also the Web Interface did not respond to this error properly. It resulted in all Browser windows and Tabs to become unusably unresponsive and the Safari took huge amounts of CPU usage.

**Comment by SgtBatten** [comment]
Post screenshot showing pairs and dca sell strategies in the GUI config. Something is missing that shouldn't be.

**Comment by taniman** [comment]
A restart did not help this errors?
