### ISSUE TITLE
Error on PT after upgrading Feeder to v.1.5.1.685

### ISSUE THREAD

**Issue by gbrottman** [taniman/profit-trailer#1722]
2018-04-30 02:27:03 INFO Application - PT Version: 1.2.6.25
2018-04-30 02:27:03 INFO Application - Java Version: 1.8.0_161
2018-04-30 02:27:21 INFO Util - Detected configuration changes
2018-04-30 02:27:21 INFO ProfitTrailerService - Normal Heartbeat
2018-04-30 02:27:21 INFO ProfitTrailerService - DCA Heartbeat
2018-04-30 02:27:24 INFO ProfitTrailerService - Cache Heartbeat
2018-04-30 02:27:24 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.A(StrategyRunnerHelper.java:741) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:70) [classes!/:1.2.6.25]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-04-30 02:27:24 ERROR NormalStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.t(StrategyRunnerHelper.java:441) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:102) [classes!/:1.2.6.25]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-04-30 02:27:25 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:181) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:150) [classes!/:1.2.6.25]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-04-30 02:27:29 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.utils.a.d.valueOf(TradeStrategy.java:3) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.A(StrategyRunnerHelper.java:741) ~[classes!/:1.2.6.25]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:70) [classes!/:1.2.6.25]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
2018-04-30 02:27:29 ERROR NormalStrategyRunner - An error occured

Any ideas? Thank you

**Comment by SgtBatten** [comment]
buy strategy issue
