### ISSUE TITLE
The PT2.0 bot makes the java broken

### ISSUE THREAD

**Issue by Gert21** [taniman/profit-trailer#1728]
At first, as it worked, but after the java update, no more work ...

```
2018-04-30` 13:54:24 INFO Application - PT Version: 2.0.1
2018-04-30 13:54:24 INFO Application - Java Version: 1.8.0_171
2018-04-30 13:54:54 INFO ProfitTrailerService - DCA Heartbeat
2018-04-30 13:54:54 INFO ProfitTrailerService - PAIRS Heartbeat
2018-04-30 13:54:55 INFO ProfitTrailerService - Cache Heartbeat
2018-04-30 13:55:01 ERROR a - An error occured
java.lang.NumberFormatException: A blank string is not a valid number
	at org.apache.commons.lang3.math.NumberUtils.createBigDecimal(NumberUtils.java:789) ~[commons-lang3-3.5.jar!/:3.5]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.a(StrategyRunnerHelper.java:1187) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:462) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:104) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.a.a(AbstractBuyStrategyRunner.java:89) [classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:70) [classes!/:2.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
2018-04-30 13:55:08 ERROR a - An error occured
```

**Comment by SgtBatten** [comment]
some part of your dca buy or sell strategy is blank or missing that needs to be present.

Come to discord for support on this.
