### ISSUE TITLE
Raspberry Crash

### ISSUE THREAD

**Issue by cyberience** [taniman/profit-trailer#1733]
Fresh update on pi and libraries as mentioned in the guide. the follwoing occures. I can still run Version 1.2 reliably on the same pi. Details below:
```
2018-04-30 23:24:28 INFO ProfitTrailerService - DCA Heartbeat
2018-04-30 23:24:30 INFO ProfitTrailerService - Cache Heartbeat
2018-04-30 23:24:38 ERROR a - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.a(StrategyCalculations.java:823) ~[classes!/:2.0.1]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.a(StrategyRunnerHelper.java:135) ~[classes!/:2.0.1]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.b(StrategyRunnerHelper.java:117) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.a(NormalStrategyRunner.java:242) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.a(NormalStrategyRunner.java:121) ~[classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.a.a(AbstractBuyStrategyRunner.java:89) [classes!/:2.0.1]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:61) [classes!/:2.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2018-04-30 23:24:44 ERROR a - An error occured
```

**Comment by YoJeff** [comment]
Yes, run this through support first.....
