### ISSUE TITLE
Incorrect average cost (bought price) after new buy

### ISSUE THREAD

**Issue by stillcollating** [taniman/profit-trailer#1859]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version:  2.0.4

 
Exchange:
- [x] Bittrex
- [x] Binance
- [x] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
I expect the correct average price to be reported in the DCA log.  

## Current Behavior
These 3 buys are the first I've had after upgrading from v1.  My bittrex account was all in BTC except for a couple dust.  All 3 buys immediately went to the DCA log.   The XVG was bought for .00000685, TRX was bought for .00000835, and SNT for .00001436.  All 3 went straight to DCA and have incorrect avg price, with XVG being WAY off.  These are the only 3 buys the bot has done, I shut it down as soon as I saw this.  

![pt](https://user-images.githubusercontent.com/13613327/40008741-0e82a902-576e-11e8-81f2-6579d33a63b2.jpg)

All 3 of those were bought and can be seen in the 10 minute log below.  I took a screenshot and shut the bot down.  

## Possible Solution
My settings are pretty simple.  My Bittrex account was entirely in BTC.  It's a completely fresh install with a fresh account.  Those were the only buys it's done.   I see no obvious reason for the bug.

## Steps to Reproduce

1.  Fresh install 2.0.4
2.  Set bot up to use Bittrex
3.  
4.

## Configuration

If you need settings, I'll send them to you privately.  I'll be on Discord as StillCollating.

## Log files/console output

 

2018-05-14 12:47:46 INFO Application - PT Version: 2.0.4
2018-05-14 12:47:46 INFO Application - Java Version: 1.8.0_161
2018-05-14 12:47:56 INFO ProfitTrailerService - Cache Heartbeat
2018-05-14 12:47:56 INFO ProfitTrailerService - PAIRS Heartbeat
2018-05-14 12:47:56 INFO ProfitTrailerService - DCA Heartbeat
2018-05-14 12:53:25 INFO ProfitTrailerService - Buy order for BTC-XVG -- {"OrderId":"27364fcd-2f39-4419-95b5-19e8564b8173","MarketName":"BTC-XVG","MarketCurrency":"XVG","BuyOrSell":"Buy","OrderType":"LIMIT","Quantity":277.37226277372264,"Rate":0.00000685}
2018-05-14 12:53:31 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"27364fcd-2f39-4419-95b5-19e8564b8173","Exchange":"BTC-XVG","Type":"LIMIT_BUY","Quantity":277.37226277,"QuantityRemaining":0.00000000,"Limit":0.00000685,"Reserved":0.00189999,"ReserveRemaining":0.00189722,"CommissionReserved":0.00000474,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000474,"Price":0.00189722,"PricePerUnit":0.00000683000000000000,"Opened":"2018-05-14T12:53:25.89","Closed":"2018-05-14T12:53:25.937","IsOpen":false,"Sentinel":"f90f8835-aaf3-4030-a7e2-8e77ee13e8b0","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
2018-05-14 12:53:31 INFO NormalStrategyRunner - Normal Pair - currency pair BTC-XVG, MTP 32, TTP 1
2018-05-14 12:53:31 INFO NormalStrategyRunner - BUYLOG: {"market":"BTC-XVG","profit":0.0,"orderbookProfit":0.0,"currentPrice":6.85E-6,"buyStrategies":[{"type":"BUY","name":"EMASPREAD","entryValue":-0.1,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":-0.2037911711957774,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."}],"sellStrategies":[],"volume":797.30722144,"percChange":-0.040673,"originalTrailingData":{"originalTrigger":0.0,"originalWidth":0.0,"originalValue":6.86E-6,"lastTrailTime":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":12,"minute":55,"second":25,"nano":725000000}}}}
2018-05-14 12:56:23 INFO ProfitTrailerService - Buy order for BTC-TRX -- {"OrderId":"edca224b-9ab2-43dc-8803-25ae6446f037","MarketName":"BTC-TRX","MarketCurrency":"TRX","BuyOrSell":"Buy","OrderType":"LIMIT","Quantity":227.54491017964074,"Rate":0.00000835}
2018-05-14 12:56:30 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"edca224b-9ab2-43dc-8803-25ae6446f037","Exchange":"BTC-TRX","Type":"LIMIT_BUY","Quantity":227.54491017,"QuantityRemaining":0.00000000,"Limit":0.00000835,"Reserved":0.00189999,"ReserveRemaining":0.00189999,"CommissionReserved":0.00000474,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000474,"Price":0.00189999,"PricePerUnit":0.00000834000000000000,"Opened":"2018-05-14T12:56:23.673","Closed":"2018-05-14T12:56:23.72","IsOpen":false,"Sentinel":"11a4a22d-dc89-4f82-9b7a-6fc2051e9f49","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
2018-05-14 12:56:30 INFO NormalStrategyRunner - Normal Pair - currency pair BTC-TRX, MTP 32, TTP 2
2018-05-14 12:56:30 INFO NormalStrategyRunner - BUYLOG: {"market":"BTC-TRX","profit":0.0,"orderbookProfit":0.0,"currentPrice":8.35E-6,"buyStrategies":[{"type":"BUY","name":"LOWBB","entryValue":12.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":40.634141884183336,"currentValuePercentage":0.0,"decimals":1,"positive":"true trailing..."}],"sellStrategies":[],"volume":794.5022703,"percChange":-0.023474,"originalTrailingData":{"originalTrigger":0.0,"originalWidth":0.0,"originalValue":8.35E-6,"lastTrailTime":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":12,"minute":58,"second":23,"nano":503000000}}}}
2018-05-14 12:56:48 INFO ProfitTrailerService - Buy order for BTC-SNT -- {"OrderId":"844d58d5-4aef-42ad-bd79-f1c1aa3b76dd","MarketName":"BTC-SNT","MarketCurrency":"SNT","BuyOrSell":"Buy","OrderType":"LIMIT","Quantity":132.31197771587745,"Rate":0.00001436}
2018-05-14 12:56:53 INFO ProfitTrailerService - Get order information -- {"AccountId":null,"OrderUuid":"844d58d5-4aef-42ad-bd79-f1c1aa3b76dd","Exchange":"BTC-SNT","Type":"LIMIT_BUY","Quantity":132.31197771,"QuantityRemaining":0.00000000,"Limit":0.00001436,"Reserved":0.00189999,"ReserveRemaining":0.00189999,"CommissionReserved":0.00000474,"CommissionReserveRemaining":0.00000000,"CommissionPaid":0.00000474,"Price":0.00189999,"PricePerUnit":0.00001435000000000000,"Opened":"2018-05-14T12:56:48.47","Closed":"2018-05-14T12:56:48.58","IsOpen":false,"Sentinel":"33206b68-1d0f-4a94-81b0-16518faa8070","CancelInitiated":false,"ImmediateOrCancel":true,"IsConditional":false,"Condition":"NONE","ConditionTarget":null}
2018-05-14 12:56:53 INFO NormalStrategyRunner - Normal Pair - currency pair BTC-SNT, MTP 32, TTP 3
2018-05-14 12:56:53 INFO NormalStrategyRunner - BUYLOG: {"market":"BTC-SNT","profit":0.0,"orderbookProfit":0.0,"currentPrice":1.436E-5,"buyStrategies":[{"type":"BUY","name":"EMAGAIN","entryValue":0.4,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":0.3338456744350182,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."}],"sellStrategies":[],"volume":76.99962072,"percChange":-0.023208,"originalTrailingData":{"originalTrigger":0.0,"originalWidth":0.0,"originalValue":1.437E-5,"lastTrailTime":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":12,"minute":58,"second":48,"nano":382000000}}}}
2018-05-14 12:57:56 INFO ProfitTrailerService - PAIRS Heartbeat
2018-05-14 12:57:58 INFO ProfitTrailerService - Cache Heartbeat
2018-05-14 12:57:59 INFO ProfitTrailerService - DCA Heartbeat
2018-05-14 13:00:46 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_161]
	at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_161]
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_161]
	at nl.komtek.pt.schedules.AllScheduledTasks.fetchData(AllScheduledTasks.java:51) ~[classes!/:2.0.4]
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by YoJeff** [comment]
I'd blur/clip  out your IP address....

**Comment by stillcollating** [comment]
pairs.properties  (All my coins are set specifically.  I've included the 3 relevant ones.)

#GENERAL SETTINGS#
market = BTC
enabled_pairs = ALL
hidden_pairs = 
DEFAULT_trading_enabled = false
DEFAULT_DCA_enabled = -2

start_balance = 0.37354912
keep_balance = 0
keep_balance_percentage = 50
orderbook_profit_calculation = true

#---------------------------------------------------------------
#INITIAL BUY SETTINGS#

max_trading_pairs = 32
DEFAULT_initial_cost = 0
DEFAULT_initial_cost_percentage = 1
DEFAULT_min_buy_volume = 50
DEFAULT_min_buy_price = 0.00000200
DEFAULT_max_buy_spread = 0.85
DEFAULT_min_orderbook_volume_percentage = 110

DEFAULT_rebuy_timeout = 15
DEFAULT_buy_min_change_percentage = -20
DEFAULT_buy_max_change_percentage = 10
pair_min_listed_days = 20

#---------------------------------------------------------------
#BUY STRATEGY#

#DEFAULT_A_buy_strategy = LOWBB
#DEFAULT_A_buy_value = -5
#DEFAULT_A_buy_value_limit = -35

#DEFAULT_B_buy_strategy = EMAGAIN
#DEFAULT_B_buy_value = -0.55
#DEFAULT_B_buy_value_limit = -2.5

#DEFAULT_C_buy_strategy = RSI
#DEFAULT_C_buy_value = 38
#DEFAULT_C_buy_value_limit = 0

DEFAULT_trailing_buy = 0.3

#---------------------------------------------------------------
#SELL STRATEGY#

DEFAULT_A_sell_strategy = GAIN
DEFAULT_A_sell_value = 1

#DEFAULT_B_sell_strategy = RSI
#DEFAULT_B_sell_value = 50

DEFAULT_trailing_profit = 0.25

DEFAULT_max_profit = 0
DEFAULT_take_profit_wait_time = 0
DEFAULT_take_profit_reset_percentage_move = 0
DEFAULT_take_profit_percentage = 0

#---------------------------------------------------------------
#SELL ONLY MODE#
DEFAULT_sell_only_mode_enabled = false

#consecutive_buy_trigger = 2
#consecutive_sell_trigger = 1

price_trigger_market = BTC
price_rise_trigger = 4
price_rise_recover_trigger = 3
price_drop_trigger = 2
price_drop_recover_trigger = 1


DEFAULT_pending_order_wait_time = 0
DEFAULT_combined_cancel_pending_trigger = 0

#---------------------------------------------------------------
#SETTINGS THAT CAN LOSE YOU MONEY
DEFAULT_panic_sell_enabled = false

DEFAULT_stop_loss_trigger = 0
DEFAULT_stop_loss_timeout = 0

#---------------------------------------------------------------
#COIN SPECIFIC SETTINGS#
BNB_trading_enabled = false

SNT_trading_enabled = true
SNT_DCA_enabled = -2
SNT_A_buy_strategy = EMAGAIN
SNT_A_buy_value = 0.4
SNT_A_sell_strategy = GAIN
SNT_A_sell_value = 1.0

TRX_trading_enabled = true
TRX_DCA_enabled = -2
TRX_A_buy_strategy = LOWBB
TRX_A_buy_value = 12.0
TRX_A_sell_strategy = GAIN
TRX_A_sell_value = 1.0

XVG_trading_enabled = true
XVG_DCA_enabled = -2
XVG_A_buy_strategy = EMASPREAD
XVG_A_buy_value = -0.1
XVG_A_sell_strategy = GAIN
XVG_A_sell_value = 1.0

**Comment by stillcollating** [comment]
indicators.properties

BB_std = 2
BB_candle_period = 300
BB_length = 5

SMA_cross_candles = 2
SMA_candle_period = 300
SMA_fast_length = 4
SMA_slow_length = 11

EMA_cross_candles = 2
EMA_candle_period = 300
EMA_fast_length = 4
EMA_slow_length = 11

RSI_candle_period = 300
RSI_length = 14

STOCH_candle_period = 300
STOCH_length = 14

MACD_candle_period = 300
MACD_fast_length = 12
MACD_slow_length = 26
MACD_signal = 9

OBV_candle_period = 300
OBV_length = 50
OBV_signal = 1

#Always uses 5 minute candles
SOM_trigger_length = 288

**Comment by stillcollating** [comment]
hoping this can be dealt with quickly.  my bot is out of commission as far as i can tell.

**Comment by alexdolli** [comment]
For what it's worth, I have the exact same issue on Binance (v2.0.4)

**Comment by ochiengj** [comment]
I am experiencing something similar. My buys are starting at deep negative, e.g. -0.6, -0.8 or more. A buy should be very close to 0.00 I believe.

**Comment by SgtBatten** [comment]
@ochiengj that is absolutely not true. Your experiencing exactly what I would expect. This is not related at all to this. If you are the same person who spoke of this on discord I explained why this is the case.

**Comment by ochiengj** [comment]
@SgtBatten Sir I don't believe we spoke on discord regarding this. My discord username is CowryShells. I posted the question asking why every time my bot buys it starts from a negative that is far from zero. I got a reply from 'Hallmonitor' saying it starts at negative because it accounts for fees. My followup question was 'why doesn't it just factor in the fees during the buy, so it can start at 0?' After a while I left discord to check here, I have not gone back to discord since then. If this issue is not related to this post then I apologize. But please don't say that my experience is not true. I am experiencing exactly as described. You have to keep in mind that us users sometimes do not know if something is a bug or if it's working as intended.  If it's not a bug just let the customer know respectfully.  I will check the discord for your reply. Thank you.

**Comment by SgtBatten** [comment]
@ochiengj Yes I added to that conversation but you never replied.

It does factor in the fees. It factors it in so that for it to be 0% profit  the price would have to be the fee amount above what you just paid for it. So 0.01% is actually profit.

As soon as you buy, you require the price to be higher than what you paid in order to make the fees back. So your target price is higher than what you paid just to break even.

I'm not sure why this isn't making sense but please contact me on discord for further info

**Comment by ChipCrypto** [comment]
Woke up to this pair in my DCA and noticed that my indicators were not even close to selling. reviewed the Chart and it appears to had recently pump'n'dumped so I Panic Sold. Noticed later that the price was completely wrong. 

![image](https://user-images.githubusercontent.com/37139161/40033356-b49d56e4-57bd-11e8-8368-797352873a16.png)

HERE IS THE PURCHASE
2018-05-14 12:13:22 INFO NormalStrategyRunner - BUYLOG: {"market":"LUNBTC","profit":0.0,"orderbookProfit":0.0,"currentPrice":0.0022559,"buyStrategies":[{"type":"BUY","name":"EMAGAIN","entryValue":-0.5,"entryValueLimit":-2.5,"triggerValue":0.0,"currentValue":-1.6041328592769855,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."},{"type":"BUY","name":"RSI","entryValue":35.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":34.79132496817466,"currentValuePercentage":0.0,"decimals":0,"positive":"true trailing..."},{"type":"BUY","name":"LOWBB","entryValue":10.0,"entryValueLimit":-20.0,"triggerValue":0.0,"currentValue":2.3236779366159204,"currentValuePercentage":0.0,"decimals":1,"positive":"true trailing..."}],"sellStrategies":[],"volume":9969.76102981,"percChange":0.09076,"originalTrailingData":{"originalTrigger":0.0,"originalWidth":0.0,"originalValue":0.0022637,"lastTrailTime":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":10,"minute":15,"second":15,"nano":82000000}}}}

HERE IS THE PANIC SELL

2018-05-14 16:29:44 INFO ProfitTrailerService - Sell order for LUNBTC sold amount 1.850000 for price 0.002210 -- {"symbol":"LUNBTC","orderId":13940215,"clientOrderId":"5ndh0zePMhXXqA71tHuINb","transactTime":1526308184092,"price":"0.00221000","origQty":"1.85000000","executedQty":"1.85000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}
2018-05-14 16:29:45 INFO Util - Detected configuration changes
2018-05-14 16:29:49 INFO ProfitTrailerService - Get order information -- {"symbol":"LUNBTC","orderId":13940215,"clientOrderId":"5ndh0zePMhXXqA71tHuINb","price":0.00221000,"origQty":1.85000000,"executedQty":1.85000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1526308184092}
2018-05-14 16:29:49 INFO StrategyRunnerHelper - SELLLOG: {"combinedProfit":0.0,"market":"LUNBTC","profit":18.28976484338978,"orderbookProfit":0.0,"averageCalculator":{"totalCost":0.003450517510000000,"totalAmount":1.85000000,"totalAmountWithSold":0,"avgPrice":0.0018651446,"avgCost":0.003450517510000000,"firstBoughtDate":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":10,"minute":13,"second":17,"nano":2000000}},"totalWeightedPrice":0.003450517510000000,"fee":0.2,"usedBuyHistory":[],"usedSellHistory":[]},"currentPrice":0.00221,"buyStrategies":[],"sellStrategies":[{"type":"SELL","name":"PANICSELL","entryValue":0.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":0.95,"currentValuePercentage":0.0,"decimals":0,"positive":"false"}],"volume":9906.19687765,"percChange":0.0}
2018-05-14 16:29:49 INFO StrategyRunnerHelper - STOREDAVG: {"currencyPair":"LUNBTC","lastBoughtDate":{"date":{"year":2018,"month":5,"day":14},"time":{"hour":10,"minute":13,"second":17,"nano":2000000}},"lastOrderId":"2154771","lastAveragePrice":0.0018651446,"boughtPrice":0.0,"lastTotalAmount":1.85000000,"overridden":false}
2018-05-14 16:31:20 INFO AverageCalculator - Please set LUN_bought_price
2018-05-14 16:31:25 ERROR GenericStrategyRunner - An error occured

After I sold it it appears to notice an unset bought price in the log.

**Comment by ChipCrypto** [comment]
And here is how it looks on Binance.

![image](https://user-images.githubusercontent.com/37139161/40033500-51465586-57be-11e8-99eb-52986c727d66.png)

**Comment by stillcollating** [comment]
Found something else that looks off.  Probably a separate issue, but maybe it has something to do with incorrect bought price as well.  As you can see from my settings, I have it set to 1% initial_cost_percentage.  1% of the .374 TCV would be 0.00374.  However, from the logs you can see the bot purchased 0.00189722 XVG, 0.00189999 TRX, 0.00189999 SNT.  Looks like it used .5% instead of 1%.    I can make make a new issue for it if you want, but it's all in the same log/screenshot.  Or maybe I just misunderstand something about initial_cost_percentage.

**Comment by SgtBatten** [comment]
It is a seperate concern yes. But Do you use keep balance? This affects initial cost percentage

**Comment by stillcollating** [comment]
keep_balance_percentage = 50

So initial cost is calculated after keep balance?  TCV * 0.5 * 0.01?    That would make it work out.  Thanks.

**Comment by SgtBatten** [comment]
Yep

**Comment by stillcollating** [comment]
I think this is cleared up in 2.0.5.   I started fresh just like before.  I got 4 buys and the bought price and bought costs look correct on all of them.  Thanks for the fix.
