### ISSUE TITLE
Issue: java.lang.IllegalStateException: Form too large: 228838 > 200000

### ISSUE THREAD

**Issue by kkoenen** [taniman/profit-trailer#2095]
## ProfitTrailer info
Version: 2.1.5

Exchange:
- [ ] Bittrex
- [X] Binance
- [ ] Poloniex

Market:
- [ ] BTC
- [X] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [X] Other linux distro, Raspbian
- [ ] Mac OS

## Expected Behavior
File from PTMagic should be parsed successfully.

## Current Behavior
Error about Form being too large. Error from jetty server. See log.

## Troubleshooting
Tried reducing pairs, can set thresholds higher, so that the number of single market settings is limited and the files (form) will be smaller. However, I think PT should be able to handle large settings files too.

## Possible Solution
Increase maximum size to maybe 500000? I don't know what the impact of this change will be on the rest of the application. The method to invoke is: ContextHandler.setMaxFormContentSize(int maxSize);

## Steps to Reproduce
Install PT. Install PTMagic. Use NorthStar settings. Don't set strict limits on pair-reducing factors like min_buy_volume.

## Configuration
PAIRS : https://pastebin.com/raw/s8LVviSp (this is a very big file)
DCA : https://pastebin.com/raw/ap4bawrm
INDICATORS : https://pastebin.com/raw/MfsmAkVL

## Log files/console output
2018-10-15 21:56:21 ERROR AppErrorController - org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
	at org.eclipse.jetty.server.Request.getParameters(Request.java:390)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1025)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Form too large: 228838 > 200000
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:541)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:471)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:386)
	... 37 more

**Comment by SgtBatten** [comment]
If you wish to use a larger config than permitted you can disable online config storage 

 https://wiki.profittrailer.com/doku.php?id=application.properties#serverdisable_online_config

**Comment by taniman** [comment]
Sorry but sounds to me like an exessive amount of data is being put into a form. So you should change your data. Remove extra comments that are not required

We don't really change our code to support addons

**Comment by taniman** [comment]
Fixed in 2.1.21

**Comment by kkoenen** [comment]
Big thanks & kudo's!
