### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#2112]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.23

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (16.04)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Bot should start

## Current Behavior
Not starting

## Troubleshooting
Bot restart

## Steps to Reproduce

1. Start bot
2.
3.
4.

## Log files/console output
2018-11-14 10:16:22 INFO Application - PT Version: 2.1.23
2018-11-14 10:16:22 INFO Application - Java Version: 1.8.0_151
2018-11-14 10:16:25 DEBUG ConfigApi - Key: .................................... - Exchange BINANCE
2018-11-14 10:16:25 DEBUG ConfigApi - selected config ........
2018-11-14 10:17:29 DEBUG Application$a - None of the document roots [src/main/webapp, public, static] point to a directory and will be ignored.
2018-11-14 10:17:29 INFO Application$a - Server initialized with port: 8081
2018-11-14 10:17:30 INFO Application - trying to shutdown...
2018-11-14 10:17:30 ERROR SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Jetty servlet container
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at nl.komtek.pt.application.Application.main(Application.java:192) [classes!/:2.1.23]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [ProfitTrailer.jar:2.1.23]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [ProfitTrailer.jar:2.1.23]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [ProfitTrailer.jar:2.1.23]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [ProfitTrailer.jar:2.1.23]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Jetty servlet container
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.initialize(JettyEmbeddedServletContainer.java:110) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.<init>(JettyEmbeddedServletContainer.java:82) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getJettyEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:563) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:191) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at nl.komtek.pt.application.Application$a.getEmbeddedServletContainer(Application.java:254) ~[classes!/:2.1.23]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	... 15 more
Caused by: java.lang.IllegalStateException: /tmp/4257EBB37212C65C30B0B5C5581C306405DDC2B9/servlet-sessions must be readable/writeable dir
	at org.eclipse.jetty.server.session.FileSessionDataStore.initializeStore(FileSessionDataStore.java:403) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.session.FileSessionDataStore.doStart(FileSessionDataStore.java:77) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.session.AbstractSessionCache.doStart(AbstractSessionCache.java:228) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.java:503) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.ScopedHandler.doStart(ScopedHandler.java:123) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:909) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370) ~[jetty-servlet-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497) ~[jetty-webapp-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459) ~[jetty-webapp-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287) ~[jetty-servlet-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) ~[jetty-webapp-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:403) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.Server.start(Server.java:419) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.server.Server.doStart(Server.java:386) ~[jetty-server-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.11.v20180605.jar!/:9.4.11.v20180605]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.initialize(JettyEmbeddedServletContainer.java:104) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.<init>(JettyEmbeddedServletContainer.java:82) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getJettyEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:563) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:191) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at nl.komtek.pt.application.Application$a.getEmbeddedServletContainer(Application.java:254) ~[classes!/:2.1.23]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.15.RELEASE.jar!/:1.5.15.RELEASE]
	... 15 more

**Comment by taniman** [comment]
Looks to me like a permissions error.  On your VPS.  So not a bug

error states
/tmp/4257EBB37212C65C30B0B5C5581C306405DDC2B9/servlet-sessions must be readable/writeable dir

**Comment by jokaorgua** [comment]
maybe would be great to have normal message about the problem ? Like "We dont have a permission for dir ....". This will be useful for self-solving errors
