### ISSUE TITLE
Gain Strategy Runner Error

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#243]
Pairs

ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_min_profit = 1
ALL_trailing_profit = 0.3
All_stop_loss_trigger = 0

ALL_DCA_enabled = false
ALL_DCA_enabled_trigger = -2

DCA:

enabled = true
max_cost = 0.005
max_buy_times = 1
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN

buy_trigger_1 = -2.0
buy_trigger_2 = -3.0
buy_trigger_3 = -3.0
buy_trigger_5 = -13.0
buy_trigger_6 = -15.0

sell_strategy = GAIN
sell_value = 0.80
max_buy_spread = 2
trailing_profit = 0.25
trailing_buy = 0.3
stop_loss_trigger = 0
pending_order_wait_time = 0
ignore_sell_only_mode = false
min_buy_balance = 0.01

2017-11-12 16:41:28 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:656) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:69) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:70) [classes!/:1.2.5.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
nov. 12, 2017 4:41:35 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-11-12 16:42:39 INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance
2017-11-12 16:43:00 INFO Util - Detected configuration changes
2017-11-12 16:43:10 INFO Util - Detected configuration changes
2017-11-12 16:47:42 INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance
2017-11-12 16:50:26 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:656) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:69) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:70) [classes!/:1.2.5.2]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-11-12 16:51:27 INFO DCAStrategyRunner - DCA Heartbeat
2017-11-12 16:51:37 INFO NormalStrategyRunner - Normal Heartbeat
2017-11-12 16:52:43 INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance
2017-11-12 16:54:40 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:656) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:69) ~[classes!/:1.2.5.2]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:70) [classes!/:1.2.5.2]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-11-12 16:57:43 INFO DCAStrategyRunner - You are not allowed to buy. Buy will exceed min buy balance

**Comment by AkliOnet** [comment]
Again new full install on the last version

**Comment by AkliOnet** [comment]
And now I get the DCA LOg empty and a red message  "There was an error while processing the data received from ProfitTrailer. Please give ProfitTrailer some love, make a coffee and all will be good soon."

**Comment by AkliOnet** [comment]
After refreshing the page , the dca log is back

**Comment by m4k3rz** [comment]
the solution for me was to use the right API address. The whole issue started because I activated a new key under a previous license I had bought. Then, I made the mistake of using that key as the default_apikey instead of the trading_apikey in the application.properties file.
