### ISSUE TITLE
ERROR: -1013 Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by ZachGoldberg** [taniman/profit-trailer#386]
```
2017-12-08 04:15:14 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
        at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:844) ~[classes!/:1.2.6-B6]
        at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$21(ProfitTrailerService.java:791) ~[classes!/:1.2.6-B6]
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
        at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:791) ~[classes!/:1.2.6-B6]
        at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:754) ~[classes!/:1.2.6-B6]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6-B6]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6aced9ca.sellOrder(<generated>) ~[classes!/:1.2.6-B6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:143) ~[classes!/:1.2.6-B6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:83) [classes!/:1.2.6-B6]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by proxyLegs** [comment]
I've got the same error as this too; not sure what's cause it though. 

I've only got this error on a instance of the bot using the Binance exchange, never got it my other instance which trades on Poloniex.

**Comment by Jamby93** [comment]
This arise from trying to sell for less than 0.001 BTC  (Binance dust level). Be sure to check that your _max_cost is higher that that, consider however that you still won't be able to sell if a loss will take value lower than dust level. 
I've also experienced some partial orders (you can see them as expired on binance) that left a decent amount of BTC value just a few drop lower than threshold; I usually buy some more of that coin to be able to sell everything (or at least trying, some dust is always present..). You can try to prevent this raising the buy_available_volume_trigger.

**Comment by bverkron** [comment]
This is filling up my logs right now.  Any way to tell which pair is causing this so I can attempt to correct it as per above?

**Comment by Jamby93** [comment]
I usually manually checked on my Binance deposit page in BTC value column a value near 0.001 (I think PT would try to sell something like 0.000868) be sure to have Hide small assets turned of; nowadays there's also the dust tab in PT.

**Comment by rtom098** [comment]
Got the same with feeder addon now.

1) I just have 1 dust, guess this is giving me the Error 1013 then. 
2) May it has something to do with this?
https://www.reddit.com/r/binance/comments/7o9hnb/binance_quietly_doubled_minimum_trade_from/

**Comment by taniman** [comment]
if this is the case please increase BTC_dust in configuration.properties to 0.00205 and set a recommended ALL_max_cost of 0.0022
