### ISSUE TITLE
ERROR GainStrategyRunner - An error occured

### ISSUE THREAD

**Issue by SallyDT** [taniman/profit-trailer#411]
2017-12-14 03:13:41 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
        at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:850) ~[classes!/:1.2.6]
        at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$22(ProfitTrailerService.java:797) ~[classes!/:1.2.6]
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
        at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:797) ~[classes!/:1.2.6]
        at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:760) ~[classes!/:1.2.6]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$3a3bda35.sellOrder(<generated>) ~[classes!/:1.2.6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:143) ~[classes!/:1.2.6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:83) [classes!/:1.2.6]
        at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by taniman** [comment]
This error means that you are trying to sell dust. Please set your dust amounts  in configuration.properties to prevent this error from occuring
