### ISSUE TITLE
ERROR NormalStrategyRunner - An error occured java.lang.NullPointerException: null - ?

### ISSUE THREAD

**Issue by SallyDT** [taniman/profit-trailer#417]
017-12-15 02:06:13 ERROR NormalStrategyRunner - An error occured
java.lang.NullPointerException: null
        at com.cf.a.a.a.a(BinancePublicAPIClient.java:126) ~[x-client-1.2.4.jar!/:?]
        at com.cf.a.a.a.a(BinancePublicAPIClient.java:108) ~[x-client-1.2.4.jar!/:?]
        at com.cf.a.a.a.getChartData(BinancePublicAPIClient.java:82) ~[x-client-1.2.4.jar!/:?]
        at com.cf.a.a.a.getChartData(BinancePublicAPIClient.java:78) ~[x-client-1.2.4.jar!/:?]
        at nl.komtek.pt.client.generic.PublicAPIClient.getChartData(PublicAPIClient.java:82) ~[x-client-1.2.4.jar!/:?]
        at nl.komtek.pt.services.ProfitTrailerService.lambda$getChartData$2(ProfitTrailerService.java:197) ~[classes!/:1.2.6]
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
        at nl.komtek.pt.services.ProfitTrailerService.getChartData(ProfitTrailerService.java:197) ~[classes!/:1.2.6]
        at nl.komtek.pt.services.ProfitTrailerService.getStaticChartData(ProfitTrailerService.java:177) ~[classes!/:1.2.6]
        at nl.komtek.pt.bot.strategy.helper.TimeSeriesHelper.createTimeSeries(TimeSeriesHelper.java:36) ~[classes!/:1.2.6]
        at nl.komtek.pt.bot.strategy.helper.StrategyCalculations.isEMABuyPositive(StrategyCalculations.java:101) ~[classes!/:1.2.6]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.buy(NormalStrategyRunner.java:178) ~[classes!/:1.2.6]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:139) [classes!/:1.2.6]
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by zin22** [comment]
im getting the same error message since yesterday

**Comment by SallyDT** [comment]
Any ideas?

**Comment by taniman** [comment]
Please ask for support regarding this in the telegram channel . also upgrade to version 1.2.6.1 that has some fixes for binance.
