### ISSUE TITLE
Constant Error. Please advise. 

### ISSUE THREAD

**Issue by zin22** [taniman/profit-trailer#425]
Please see the below error which has been appearing on My bittrex BTC BOT since the new release. All heartbeats update as usual before this but then this error occurs . 

2017-12-16 09:46:36 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
	at java.util.AbstractCollection.toArray(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_151]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:718) ~[classes!/:1.2.6]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:74) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:67) [classes!/:1.2.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-16 09:47:45 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
	at java.util.AbstractCollection.toArray(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_151]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:718) ~[classes!/:1.2.6]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:74) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:67) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by taniman** [comment]
Please update to 1.2.6.1 see if this helps with this problem

**Comment by zin22** [comment]
I did. Still occurs. On both my bittrex bots 
And consecutive buy trigger does not work.
