### ISSUE TITLE
[Errors] 2 Bots (1x Pi / 1x PC) - throwing errors / each seperately working without issues

### ISSUE THREAD

**Issue by Pintinero** [taniman/profit-trailer#434]
Hi! I have 1x bittrex(BTC market) running on a Pi (ProfitPi - CryptoGnome) and want to run another bot on Binance(USDT) on my PC.
I just get these errors when both bots run in parallel.
Each bot is running on different ports

When I start the binance bot it get the following error from **Bittrex (Pi):**
`2017-12-17 14:02:01 INFO ProfitTrailerService - Occured in ticker, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:02 INFO ProfitTrailerService - Occured in volume, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:02 INFO ProfitTrailerService - Occured in volume, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:08 INFO ProfitTrailerService - Occured in volume, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:12 INFO ProfitTrailerService - Occured in ticker, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:14 INFO ProfitTrailerService - Occured in balacnes, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:16 INFO ProfitTrailerService - Occured in CB, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:20 INFO ProfitTrailerService - Occured in volume, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:22 INFO ProfitTrailerService - Occured in chartData, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:24 INFO ProfitTrailerService - Occured in chartData, result: 200 - We got some incorrect data from the exchange - 
2017-12-17 14:02:26 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:70) ~[classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

the bot for **Binance(PC)** shows the following
`2017-12-17 14:03:36 ERROR AllScheduledTasks - java.lang.reflect.UndeclaredThrowableException
java.lang.reflect.UndeclaredThrowableException: null
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$17f1bad6.getTickerScheduled(<generated>) ~[classes!/:1.2.6]
	at nl.komtek.pt.schedules.AllScheduledTasks.updateTicker(AllScheduledTasks.java:58) [classes!/:1.2.6]
	at nl.komtek.pt.schedules.AllScheduledTasks.fetchData(AllScheduledTasks.java:42) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: com.webcerebrium.binance.api.BinanceApiException: Error in reading response Connection timed out: connect
	at com.webcerebrium.binance.api.BinanceRequest.read(BinanceRequest.java:277) ~[binance-api-1.0.5.1.jar!/:?]
	at com.webcerebrium.binance.api.BinanceApi.allPrices(BinanceApi.java:292) ~[binance-api-1.0.5.1.jar!/:?]
	at com.webcerebrium.binance.api.BinanceApi.pricesMap(BinanceApi.java:303) ~[binance-api-1.0.5.1.jar!/:?]
	at com.cf.data.map.generic.DataMapper.mapTickersForCurrency(DataMapper.java:115) ~[x-client-1.2.4.jar!/:?]
	at nl.komtek.pt.services.ProfitTrailerService.getTickerScheduled(ProfitTrailerService.java:256) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	... 15 more`

**Comment by taniman** [comment]
Looks like a system speicific setup problem. Better handled in 1 of our Telegram support channels

**Comment by stelians** [comment]
Hi,

I have encountered this same issue:
2017-12-17 14:03:36 ERROR AllScheduledTasks - java.lang.reflect.UndeclaredThrowableException 

what is the resolution?

Regards,
Stelian

**Comment by makeithatton** [comment]
What was your resolve you should post it here it would be very helpful for the next person

**Comment by Seabhac1** [comment]
I have also got 'ERROR AllScheduledTasks - null' Binance CryptoGnome settings.

**Comment by makeithatton** [comment]
The Resolution is that you have to download a different version of Profit trailer and input all your API keys in again then it’ll work fine!

**Comment by Seabhac1** [comment]
Thank you makeithatton. How do you know this?

**Comment by Seabhac1** [comment]
By the way I'm on version 1.2.6.11 is there a newer release or do I need to back to an older version? Thanks

**Comment by makeithatton** [comment]
Because I did it on my computer when I had the same error message reported I looked all over internet No one had an answer for me so I downloaded another version of PT reinstalled my API keys and viola I was back to normal !!


Sent from Yahoo Mail for iPhone


On Sunday, January 21, 2018, 2:19 PM, Seabhac1 <notifications@github.com> wrote:


Thank you makeithatton. How do you know this?
