### ISSUE TITLE
Profit Trailer not working

### ISSUE THREAD

**Issue by Valrion** [taniman/profit-trailer#443]
Hi
I seem to have a bit of trouble with PT it does not buy or sell anything and I get these errors :
2017-12-19 13:54:03 ERROR ProfitTrailerService - Something is really wrong
java.lang.NullPointerException: null
    at nl.komtek.pt.services.ProfitTrailerService.getBalancesScheduled(ProfitTrailerService.java:514) [classes!/:1.2.6]
    at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) [classes!/:1.2.6]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) [spring-aop-
and this 
2017-12-19 14:02:10 INFO ProfitTrailerService - Occured in CB, result: {"error":"Internal error. Please try again."}
2017-12-19 14:02:28 ERROR ProfitTrailerService - Occured in For input string: "Internal error. Please try again.", handled result exception {}
2017-12-19 14:02:28 INFO ProfitTrailerService - Occured in balacnes, result: {"error":"Internal error. Please try again."}

Any help would be appreciated!

**Comment by taniman** [comment]
please contact us on telegrm for setup support
