### ISSUE TITLE
Something is really wrong exception (Binance)

### ISSUE THREAD

**Issue by krims0n32** [taniman/profit-trailer#449]
Started getting these. Bot restart does not help.

2017-12-20 10:33:50 ERROR ProfitTrailerService - Something is really wrong
java.lang.NullPointerException: null
	at com.cf.data.map.generic.DataConverter.convertDailyInfoBinance(DataConverter.java:646) ~[x-client-1.2.4.jar!/:?]
	at com.cf.data.map.generic.DataMapper.map24hInfo(DataMapper.java:333) ~[x-client-1.2.4.jar!/:?]
	at nl.komtek.pt.services.ProfitTrailerService.getDailyInfo(ProfitTrailerService.java:273) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$1844fe5f.getDailyInfo(<generated>) ~[classes!/:1.2.6]
	at nl.komtek.pt.schedules.PublicServerScheduledTasks.lambda$updateData$0(PublicServerScheduledTasks.java:48) ~[classes!/:1.2.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:632) [?:?]
	at java.lang.Thread.run(Thread.java:804) [?:?]
2017-12-20 10:33:50 INFO ProfitTrailerService - Occured in 24hInfo, result: {}

**Comment by taniman** [comment]
Please use our telegram support Channels. Also upgrade to 1.2.6.1 as there are some binance enhancements in there
