### ISSUE TITLE
Binance Error - ERROR ProfitTrailerService - Something is really wrong

### ISSUE THREAD

**Issue by ben7700** [taniman/profit-trailer#450]
This just started happening

Getting errors on Binance. Just started. Anyone else getting?  ERROR ProfitTrailerService - Something is really wrong
ERROR ProfitTrailerService - Something is really wrong
java.lang.NullPointerException: null
	at com.cf.data.map.generic.DataConverter.convertDailyInfoBinance(DataConverter.java:646) ~[x-client-1.2.4.jar!/:?]
	at com.cf.data.map.generic.DataMapper.map24hInfo(DataMapper.java:333) ~[x-client-1.2.4.jar!/:?]
	at nl.komtek.pt.services.ProfitTrailerService.getDailyInfo(ProfitTrailerService.java:273) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$38612ccc.getDailyInfo(<generated>) ~[classes!/:1.2.6]
	at nl.komtek.pt.schedules.PublicServerScheduledTasks.lambda$updateData$0(PublicServerScheduledTasks.java:48) ~[classes!/:1.2.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-20 17:25:00 INFO ProfitTrailerService - Occured in 24hInfo, result: {}
2017-12-20 17:25:02 INFO ProfitTrailerService - Buy order for WTCBTC -- {"symbol":"WTCBTC","orderId":6139376,"clientOrderId":"2HT9UkPLGa31ck7FYni7uT","transactTime":1513765507472,"price":"0.00082811","origQty":"18.00000000","executedQty":"18.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}

**Comment by moses-aronov** [comment]
Same issue

**Comment by benzo8** [comment]
Adding another data point. Same issue here.

**Comment by taniman** [comment]
Setup errors are better handled in telegram. Please contact 1 of the admins
