### ISSUE TITLE
ERROR: -2010, Account has insufficient balance for requested action. (Binance)

### ISSUE THREAD

**Issue by krims0n32** [taniman/profit-trailer#452]
Getting error below when PT tries to sell on Binance. There is plenty of BNB present and the sell DOES come through. But because of the error PT does not see this (immediately). No telegram message is sent and the sale does not show up in the sales log.

2017-12-20 14:37:08 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -2010, Account has insufficient balance for requested action.
	at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:850) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$22(ProfitTrailerService.java:797) ~[classes!/:1.2.6]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:797) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:760) ~[classes!/:1.2.6]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$1844fe5f.sellOrder(<generated>) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:143) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:83) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:531) ~[?:?]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:632) [?:?]
	at java.lang.Thread.run(Thread.java:804) [?:?]

**Comment by krims0n32** [comment]
![screenshot_2017-12-20_15-43-03](https://user-images.githubusercontent.com/661853/34212412-847144f0-e59c-11e7-8bfa-b01bd5a72d69.png)

Screenshot of the sell order in question.

**Comment by benzo8** [comment]
I'm also seeing this behaviour.

**Comment by taniman** [comment]
Yes. Api inconsistent repsonses can cause sales log to no update correctly.
Please always use your exchange trade history as the 1 source of truth
