### ISSUE TITLE
Error: GainStrategyRunner (Bittrex)

### ISSUE THREAD

**Issue by johnalindogan** [taniman/profit-trailer#483]
All of a sudden Ive been getting this error in my console starting about 6-8hours ago. no change in config. i've already restarted bot and server. Running on v1.2.6.6.

-----------------------------------

2017-12-27 13:15:24 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
        at java.util.AbstractCollection.finishToArray(Unknown Source) ~[?:1.8.0_151]
        at java.util.AbstractCollection.toArray(Unknown Source) ~[?:1.8.0_151]
        at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:729) ~[classes!/:1.2.6.6]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:74) ~[classes!/:1.2.6.6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:77) [classes!/:1.2.6.6]
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-27 13:15:52 INFO ProfitTrailerService - Normal Heartbeat
2017-12-27 13:15:54 INFO ProfitTrailerService - DCA Heartbeat
2017-12-27 13:15:55 INFO ProfitTrailerService - Cache Heartbeat

![image](https://user-images.githubusercontent.com/15606255/34371467-6e6aa5d6-eb08-11e7-8875-925d2d662e03.png)

**Comment by johnalindogan** [comment]
update -- i've checked my logs, it seems that ive been getting this error for several days now. but error message is getting more frequent as the days go by and today its flooding my console

**Comment by johnalindogan** [comment]
update -- i'm seeing some sells. it looks like bot is able to operate despite the error. i just hope its not making me miss any potential sells.

**Comment by johnalindogan** [comment]
update -- i've recreated my config files based on the ones that came out from v1.2.6.6 but still getting the same error messages. i'm able to make buys and sells. the error messages are just a bit worrisome. i'm forced to restart the both every other hour to make sure it is chugging along properly. 

the only thing left that i have not recreated is my ProfitTrailerData.json file. i'm wondering if there might be some garbage data mixed in there somehow?

**Comment by m4k3rz** [comment]
I'm having the exact same error

2017-12-29 22:28:26 ERROR ProfitTrailerService - Tradehistory - INVALID_PERMISSION
2017-12-29 22:28:26 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.handleResultException(ProfitTrailerService.java:899) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getTradeHistoryScheduled(ProfitTrailerService.java:404) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getTradeHistory(ProfitTrailerService.java:382) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$8fab78bb.getTradeHistory(<generated>) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:82) [classes!/:1.2.6.7]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by johnalindogan** [comment]
so far I have been running version 1.2.6.8 for about a day already and have not encountered this error anymore. woot woot! thanks @elroy!
