### ISSUE TITLE
ERROR NormalStrategyRunner - ERROR DCAStrategyRunner - ERROR GainStrategyRunner

### ISSUE THREAD

**Issue by art5000** [taniman/profit-trailer#484]
Hi, since this Morning I have issues on the following setuo:

Vultr, Ubuntu VPS, running 2 instances on 2 ports for bittrex and binance.

Binance is working fine, however, bittrex shows this error below since around 5 hours.

**What I tried:**

- Update to 1.6.6.2 > Cant update - Page not loading (it worked smooth to update on Binance)

- Replace all trading files with the standard ones > No change in errors

- Reload the bot with pm2, restart server > Status = online and I can acces the dashboard, but I just doesn't pull the data

`2017-12-27 04:52:21 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getDCAMonitoringData(StrategyRunnerHelper.java:700) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:100) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-12-27 04:52:23 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
2017-12-27 04:52:26 ERROR NormalStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.utils.Util.getTotalPairsCost(Util.java:410) ~[classes!/:1.2.6]
	at nl.komtek.pt.utils.Util.getTotalCost(Util.java:429) ~[classes!/:1.2.6]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getMinBuyBalance(StrategyRunnerHelper.java:483) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.buy(NormalStrategyRunner.java:197) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:139) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-12-27 04:52:26 ERROR DCAStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getDCAMonitoringData(StrategyRunnerHelper.java:700) ~[classes!/:1.2.6]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:100) [classes!/:1.2.6]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
`

![screenshot at dec 27 12-55-44](https://user-images.githubusercontent.com/34878705/34372152-72d8e7de-eb05-11e7-8810-cb2082dd7d97.png)

**Comment by art5000** [comment]
FIXED: My ProfitTrailerData.json file was corrupted by a restart of the server and the backup file got corrupted too. UNfortunately I found both files being empty on my FTP.

Deleteing these files and reloading the bot fixed it, but I lost all previous data from 2weeks, plus lost the DCA buys - be careful when restarting the bot and you have DCA bags!

**Comment by parimal21** [comment]
I'm having the same issue. Im getting ERROR NormalStrategyRun. I'm setting up my bot for  the first time. How did you restart the bot? Did you delete all files and did a fresh download? I have the latest version and using Poloniex exchange. I have done no trade using my bot
