### ISSUE TITLE
API Errors - JsonNull (Bittrex)

### ISSUE THREAD

**Issue by c64audio** [taniman/profit-trailer#514]
Intermittent buy errors
2017-12-29 21:34:30 ERROR ProfitTrailerService - Error occured in buy, message J
sonNull, result: {"OrderId":"c3daf904-6bfd-459a-b383-2511ab254c4b","MarketName":
"BTC-SHIFT","MarketCurrency":"SHIFT","BuyOrSell":"Buy","OrderType":"LIMIT","Quan
tity":10.85537793515204,"Rate":0.00077381}

Is this Bittrex's fault? Performance on Bittrex has greatly degraded to the extent of just giving up entirely overnight and giving up hours of possible trades.

Also, I'd like to second that the current version (1.2.6.6) has that concurrent LinkedHashMap access presumably caused by odd threading behaviour.

2017-12-29 19:44:09 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~
[?:1.8.0_151]
        at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.
8.0_151]
        at java.util.AbstractCollection.toArray(Unknown Source) ~[?:1.8.0_151]
        at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonit
oringData(StrategyRunnerHelper.java:729) ~[classes!/:1.2.6.6]
        at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(Stra
tegyRunnerHelper.java:74) ~[classes!/:1.2.6.6]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(Gain
StrategyRunner.java:77) [classes!/:1.2.6.6]

**Comment by m4k3rz** [comment]
the solution for me was to use the right API address. The whole issue started because I activated a new key under a previous license I had bought. Then, I made the mistake of using that key as the default_apikey instead of the trading_apikey in the application.properties file.

**Comment by c64audio** [comment]
No, I wasn't doing that, this seems to be the Bittrex API behaving crappily under strain.
