### ISSUE TITLE
ERROR ProfitTrailerService - Tradehistory - INVALID_PERMISSION ERROR GainStrategyRunner - An error occured

### ISSUE THREAD

**Issue by m4k3rz** [taniman/profit-trailer#519]
I've been getting this error on my PT Bittrex BTC. please help

 2017-12-29 22:28:26 ERROR ProfitTrailerService - Tradehistory - INVALID_PERMISSION
2017-12-29 22:28:26 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.handleResultException(ProfitTrailerService.java:899) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getTradeHistoryScheduled(ProfitTrailerService.java:404) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getTradeHistory(ProfitTrailerService.java:382) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$8fab78bb.getTradeHistory(<generated>) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:82) [classes!/:1.2.6.7]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by m4k3rz** [comment]
the solution for me was to use the right API address. The whole issue started because I activated a new key under a previous license I had bought. Then, I made the mistake of using that key as the default_apikey instead of the trading_apikey in the application.properties file.

**Comment by taniman** [comment]
INVALID_PERMISSION is a setup problem and not an issue. Please follow the instructions properly or contact our support if you have doubts. This is not a software issue
