### ISSUE TITLE
Bittrex issues on 1.2.6.7 with _151 java

### ISSUE THREAD

**Issue by razorseal** [taniman/profit-trailer#522]
I can't get bittrex to even stay open, immedeate errors upon launch. I don't see others complaining of it, so I don't think this is bittrex related.

`2017-12-30 07:21:46 ERROR GainStrategyRunner - An error occured
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_151]
	at java.util.AbstractCollection.toArray(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.<init>(Unknown Source) ~[?:1.8.0_151]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getLastDCAMonitoringData(StrategyRunnerHelper.java:729) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.DCAEnabled(StrategyRunnerHelper.java:74) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:77) [classes!/:1.2.6.7]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-30 07:21:56 INFO ProfitTrailerService - DCA Heartbeat
2017-12-30 07:29:43 INFO Util - Detected configuration changes
2017-12-30 07:29:43 INFO ProfitTrailerService - Cache Heartbeat
2017-12-30 07:29:43 INFO ProfitTrailerService - Normal Heartbeat
2017-12-30 07:29:43 INFO ProfitTrailerService - DCA Heartbeat
2017-12-30 07:39:43 INFO ProfitTrailerService - Cache Heartbeat
2017-12-30 07:39:44 INFO ProfitTrailerService - Normal Heartbeat
2017-12-30 07:39:47 INFO ProfitTrailerService - DCA Heartbeat
2017-12-30 07:40:45 INFO DCAStrategyRunner - API Problems?
2017-12-30 07:40:49 INFO NormalStrategyRunner - API Problems?
2017-12-30 07:40:50 INFO DCAStrategyRunner - API Problems?
2017-12-30 07:40:54 INFO NormalStrategyRunner - API Problems?
2017-12-30 07:40:55 INFO DCAStrategyRunner - API Problems?
2017-12-30 07:56:45 INFO Util - Detected configuration changes
2017-12-30 07:56:45 INFO ProfitTrailerService - Cache Heartbeat
2017-12-30 07:56:46 INFO ProfitTrailerService - Normal Heartbeat
2017-12-30 07:56:46 INFO ProfitTrailerService - DCA Heartbeat
2017-12-30 07:56:55 ERROR ProfitTrailerService - balances - INVALID_SIGNATURE
2017-12-30 07:56:55 ERROR GainStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.handleResultException(ProfitTrailerService.java:899) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getBalancesScheduled(ProfitTrailerService.java:503) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getBalanceForMarket(ProfitTrailerService.java:480) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$38612ccc.getBalanceForMarket(<generated>) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:45) [classes!/:1.2.6.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-30 07:56:56 ERROR ProfitTrailerService - balances - INVALID_SIGNATURE
2017-12-30 07:57:06 ERROR ProfitTrailerService - openOrders - INVALID_SIGNATURE
2017-12-30 07:57:06 ERROR GenericStrategyRunner - An error occured
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.handleResultException(ProfitTrailerService.java:899) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getOpenOrdersScheduled(ProfitTrailerService.java:544) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getOpenOrders(ProfitTrailerService.java:521) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport$1.call(CacheAspectSupport.java:367) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.loadValue(EhCacheCache.java:99) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:86) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$38612ccc.getOpenOrders(<generated>) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.checkPendingOrders(GenericStrategyRunner.java:231) [classes!/:1.2.6.7]
	at nl.komtek.pt.strategyrunner.GenericStrategyRunner.genericStrategyRunner(GenericStrategyRunner.java:76) [classes!/:1.2.6.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2017-12-30 07:57:08 ERROR ProfitTrailerService - openOrders - INVALID_SIGNATURE
2017-12-30 07:57:08 ERROR DefaultScheduledTasks - java.lang.NullPointerException
java.lang.NullPointerException: null
	at nl.komtek.pt.services.ProfitTrailerService.handleResultException(ProfitTrailerService.java:899) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService.getOpenOrdersScheduled(ProfitTrailerService.java:544) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$38612ccc.getOpenOrdersScheduled(<generated>) ~[classes!/:1.2.6.7]
	at nl.komtek.pt.schedules.DefaultScheduledTasks.updateOpenOrders(DefaultScheduledTasks.java:99) [classes!/:1.2.6.7]
	at nl.komtek.pt.schedules.DefaultScheduledTasks.fetchData(DefaultScheduledTasks.java:63) [classes!/:1.2.6.7]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
`

**Comment by taniman** [comment]
If others are running fine. It would indicate some specific error. Please contact supprot as this is not an issue

**Comment by razorseal** [comment]
What support am I connecting? on telegram???

**Comment by taniman** [comment]
Yes. just contact me or one of the resellers directly if you gettign no response from the channel users

**Comment by razorseal** [comment]
What is your handle? I can't seem to get help from any of the users on there

**Comment by DjCoke** [comment]
I have the same issue

**Comment by DjCoke** [comment]
It does not load the coins up in the gui as well

**Comment by DjCoke** [comment]
It is over, surely it is an api thing

**Comment by taniman** [comment]
Yes. all related to invalid_signature That needs to be fixed in order for the bot to work correctly.
try this
https://wiki.profittrailer.io/doku.php/known_issues
