### ISSUE TITLE
Division undefined

### ISSUE THREAD

**Issue by murl** [taniman/profit-trailer#529]
ubuntu vps, current pt version = 1.2.6.7 jar

 2017-12-31 23:24 -05:00: 2017-12-31 23:24:25 ERROR NormalStrategyRunner - An error occured
0|profit-t | java.lang.ArithmeticException: Division undefined
0|profit-t |    at java.math.BigDecimal.divide(BigDecimal.java:1741) ~[?:1.8.0_151]
0|profit-t |    at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:128) [classes!/:1.2.6.7]
0|profit-t |    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
0|profit-t |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
0|profit-t |    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
0|profit-t |    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|profit-t |    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|profit-t |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
0|profit-t |    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
0|profit-t | 2017-12-31 23:24 -05:00: 2017-12-31 23:24:31 ERROR NormalStrategyRunner - An error occured
0|profit-t | java.lang.ArithmeticException: Division undefined
0|profit-t |    at java.math.BigDecimal.divide(BigDecimal.java:1741) ~[?:1.8.0_151]
0|profit-t |    at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:128) [classes!/:1.2.6.7]
0|profit-t |    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
0|profit-t |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
0|profit-t |    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
0|profit-t |    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|profit-t |    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|profit-t |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
0|profit-t |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
0|profit-t |    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by t3ja** [comment]
Facing the same issue on Mac OS HighSierra(version 10.13.2)

PT version - 1.2.6.7

**Comment by rer0dgers** [comment]
Many man people complaining about it in their Discord channels.

**Comment by t3ja** [comment]
@nAffie @taniman @RchGrav 
somebody please help with a quick fix at least. Is there any previous stable version?
(Sorry to spoil the party but some of us on the other side of the world are up and working)

**Comment by oneezy** [comment]
Confirmed issue for `Version 1.2.6.7`

```
2018-01-01 04:11:22 ERROR NormalStrategyRunner - An error occured
java.lang.ArithmeticException: Division undefined
        at java.math.BigDecimal.divide(Unknown Source) ~[?:1.8.0_151]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:128) [classes!/:1.2.6.7]
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```
