### ISSUE TITLE
ERROR GainStrategyRunner - An error occured

### ISSUE THREAD

**Issue by sks36** [taniman/profit-trailer#584]
keep getting below error.  please help:

2018-01-06 00:43:55 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
        at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.8]
        at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
        at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
        at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:768) ~[classes!/:1.2.6.8]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.8]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$a956ac7.sellOrder(<generated>) ~[classes!/:1.2.6.8]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by chrismpalmer** [comment]
I am also getting this error.

2018-01-05 23:31:07 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
	at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]

**Comment by sks36** [comment]
It looks like i figured the issue few min ago, but still testing.  i think it is because of binance minimum sell value increase.  i changed dust setting to below in configuration properties..  

BTC_dust = 0.00205

Link I referred: https://wiki.profittrailer.io/doku.php/configuration.properties

**Comment by chrismpalmer** [comment]
That has to be in configuration.properties?

**Comment by sks36** [comment]
yes

**Comment by chrismpalmer** [comment]
Thanks, log then says : 

2018-01-05 23:39:44 INFO ProfitTrailerService - Cannot sell BNTBTC. You are trying to sell DUST!
2018-01-05 23:39:48 INFO ProfitTrailerService - Cannot sell OAXBTC. You are trying to sell DUST!

**Comment by chrismpalmer** [comment]
Looks like that fixed my problem. I am not completely clear of the impact but its running without error and sweeps to dust

**Comment by Gitulu** [comment]
Hello guys,

The same for me over night by Binance in a loop.
I have replaced the following files: "ProfitTrailer.jar", "ProfitTrailer.cmd", "pm2-ProfitTrailer.json" again from the newest version but I still get the error.

`2018-01-06 09:37:05 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
	at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:768) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.8]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$76391a98.sellOrder(<generated>) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by Gitulu** [comment]
@sks36 Thanks I have added the parameter: "BTC_dust = 0.00205" as you have said. It seems this help. I have to monitor this.

**Comment by grandmore** [comment]
I have the same errors.

I have added all the suggestions from PTAnnouce but I still get a flood of the MIN_NOTIONAL errors. 

1. Added ALL_max_cost and disabled  ALL_max_cost_percentage for the moment so that the cost is not too small because its a percentage fo the balance.
(added) ALL_max_cost = 0.0025
(disabled) ALL_max_cost_percentage = 8

2. Added Dust settings to configuration.
BTC_dust = 0.00205
ETH_dust = 0.0105
BNB_dust = 0.0105
USDT_dust = 1.05

3. Added every XXXXXX_min_buy_price from Binance from [their list](https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule) to 
ETHBTC_min_buy_price = 0.000001
LTCBTC_min_buy_price = 0.000001
BNBBTC_min_buy_price = 0.00000001
... etc etc

4. I'am streaming the error log from stdout to Papertrails to make it easier I can grant you access and you can see all of them yourself.

There is ample balance (0.04231724BTC)

Here are some hilights:

-  MIN_NOTIONAL log

Jan 06 13:29:43 4f3aef37341a pt_app_1: 2018-01-06 13:29:43 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:30:00 bc331948866e pt_app_1: 2018-01-06 13:30:00 INFO ProfitTrailerService - SOM is active for CTRBTC. -- Manually set in PAIRS.properties 
Jan 06 13:30:05 4f3aef37341a pt_app_1: 2018-01-06 13:30:05 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:30:58 4f3aef37341a pt_app_1: 2018-01-06 13:30:58 INFO DCAStrategyRunner - There is not enough volume to make a successfull DCA ETCBTC 
Jan 06 13:31:02 bc331948866e pt_app_1: 2018-01-06 13:31:02 INFO NormalStrategyRunner - There is not enough volume to buy POEBTC 
Jan 06 13:31:07 4f3aef37341a pt_app_1: 2018-01-06 13:31:07 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:32:16 bc331948866e pt_app_1: 2018-01-06 13:32:16 INFO ProfitTrailerService - SOM is active for LSKBTC. -- Manually set in PAIRS.properties 
Jan 06 13:32:33 bc331948866e pt_app_1: 2018-01-06 13:32:33 INFO ProfitTrailerService - SOM is active for POEBTC. -- Manually set in PAIRS.properties 
Jan 06 13:32:54 4f3aef37341a pt_app_1: 2018-01-06 13:32:54 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:33:03 bc331948866e pt_app_1: 2018-01-06 13:33:03 INFO Util - Detected configuration changes 
Jan 06 13:33:16 4f3aef37341a pt_app_1: 2018-01-06 13:33:16 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:33:42 4f3aef37341a pt_app_1: 2018-01-06 13:33:42 INFO ProfitTrailerService - DCA Heartbeat 
Jan 06 13:33:44 4f3aef37341a pt_app_1: 2018-01-06 13:33:44 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:34:05 4f3aef37341a pt_app_1: 2018-01-06 13:34:05 INFO DCAStrategyRunner - There is not enough volume to make a successfull DCA ETCBTC 
Jan 06 13:34:28 4f3aef37341a pt_app_1: 2018-01-06 13:34:28 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -1013, Filter failure: MIN_NOTIONAL, result:  
Jan 06 13:34:28 bc331948866e pt_app_1: 2018-01-06 13:34:28 INFO ProfitTrailerService - SOM is active for ARNBTC. -- Manually set in PAIRS.properties 
Jan 06 13:34:46 bc331948866e pt_app_1: 2018-01-06 13:34:46 INFO ProfitTrailerService - SOM is active for DLTBTC. -- Manually set in PAIRS.properties 
Jan 06 13:34:57 bc331948866e pt_app_1: 2018-01-06 13:34:57 INFO ProfitTrailerService - SOM is active for ENJBTC. -- Manually set in PAIRS.properties 
Jan 06 13:35:03 bc331948866e pt_app_1: 2018-01-06 13:35:03 INFO ProfitTrailerService - Normal 

- ERROR: -2010, Account has insufficient balance for requested action. 

Jan 06 03:27:27 bc331948866e pt_app_1: 2018-01-06 03:27:27 INFO ProfitTrailerService - Sell order for XVGBTC sold amount 423.000000 for price 0.000010 -- {"symbol":"XVGBTC","orderId":10254287,"clientOrderId":"dDBNcGiMTk1gA8Zl1ZsDY0","transactTime":1515209247308,"price":"0.00001015","origQty":"423.00000000","executedQty":"0.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL"} 
Jan 06 03:27:32 bc331948866e pt_app_1: 2018-01-06 03:27:32 INFO ProfitTrailerService - Get order information -- {"symbol":"XVGBTC","orderId":10254287,"clientOrderId":"dDBNcGiMTk1gA8Zl1ZsDY0","price":0.00001015,"origQty":423.00000000,"executedQty":0E-8,"status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1515209247308} 
Jan 06 03:27:41 bc331948866e pt_app_1: 2018-01-06 03:27:41 INFO ProfitTrailerService - Sell order for XVGBTC sold amount 423.000000 for price 0.000010 -- {"symbol":"XVGBTC","orderId":10254376,"clientOrderId":"UuYvitxBknKTRkMDnNdkFl","transactTime":1515209261090,"price":"0.00001015","origQty":"423.00000000","executedQty":"423.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"} 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:768) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 2018-01-06 03:27:42 ERROR GainStrategyRunner - An error occured 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6d0894d2.sellOrder(<generated>) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: nl.komtek.pt.utils.PTHandledErrorException: ERROR: -2010, Account has insufficient balance for requested action. 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:805) ~[classes!/:1.2.6.8] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151] 
Jan 06 03:27:42 4f3aef37341a pt_app_1: 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151] 
Jan 06 03:27:46 bc331948866e pt_app_1: 2018-01-06 03:27:46 INFO ProfitTrailerService - Get order information -- {"symbol":"XVGBTC","orderId":10254376,"clientOrderId":"UuYvitxBknKTRkMDnNdkFl","price":0.00001015,"origQty":423.00000000,"executedQty":423.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time":1515209261090} 
Jan 06 03:27:48 bc331948866e pt_app_1: 2018-01-06 03:27:47 INFO TelegramService - We got a response Not Found 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 2018-01-06 03:27:49 ERROR GainStrategyRunner - An error occured 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$6d0894d2.sellOrder(<generated>) ~[classes!/:1.2.6.8] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.8] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.8] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151] 
Jan 06 03:27:49 4f3aef37341a pt_app_1: nl.komtek.pt.utils.PTHandledErrorException: ERROR: -2010, Account has insufficient balance for requested action.

**Comment by makeithatton** [comment]
Were you ever able to get it fixed if so can you please post a solution to the problem thx

**Comment by questforneo** [comment]
same here.. please I have the same error...is there a solution to the error message "ERROR ProfitTrailerService - Error occured in buy, message ERROR: -2010, Account has insufficient balance for requested action., result:"

**Comment by JayLucky** [comment]
Getting that error as well

2018-02-08 00:19:31 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.b: ERROR: -2010, Account has insufficient balance for requested action.
	at nl.komtek.pt.services.ProfitTrailerService.d(ProfitTrailerService.java:902) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:844) ~[classes!/:1.2.6.15]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.b(ProfitTrailerService.java:844) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:807) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.15]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$200200a2.a(<generated>) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.a(GainStrategyRunner.java:154) ~[classes!/:1.2.6.15]
	at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:89) [classes!/:1.2.6.15]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
