### ISSUE TITLE
ERROR ProfitTrailerService - Error occured in chartData, message java.lang.IllegalStateException

### ISSUE THREAD

**Issue by leeed1993** [taniman/profit-trailer#634]
Hi I recently started getting this error ever since I updated to the new PT. And I have no clue what I am supposed to do. 

ERROR ProfitTrailerService - Error occured in chartData, message java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $, result: Bittrex does not support this period

Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

These are the two errors that keep popping up on my CMD and its been doing this for a few hours now.

**Comment by oliverb456** [comment]
Mine too.

**Comment by leeed1993** [comment]
Does your PT still buy and sell while this is going on?

**Comment by oliverb456** [comment]
No. The monitor just shows my balances and pairs.

No trades and my buying strategies all say false.

**Comment by leeed1993** [comment]
Oh okay I havent seen my bot do anything so far since this error started happening either so I had to ask

**Comment by taniman** [comment]
what version of the bot is this?

**Comment by taniman** [comment]
ooh I see it.
Bittrex does not support this period.. is the message

please fix indicators.properties to a valid period.
supported periods per exchange can be found on the wiki

**Comment by Emmanueldearmas** [comment]
Porque tengo este problema? muchas gracias



2018-07-01 04:06:31 INFO ProfitTrailerService - PAIRS Heartbeat
2018-07-01 04:07:26 ERROR ProfitTrailerService - Error occured in ticker, message No value was returned, result: 
2018-07-01 04:07:51 ERROR ProfitTrailerService - Error occured in chartData, message No value was returned, result: 
2018-07-01 04:08:09 ERROR ProfitTrailerService - Error occured in volume, message No value was returned, result: 
2018-07-01 04:08:36 ERROR ProfitTrailerService - Error occured in OO, message No value was returned, result: 
2018-07-01 04:08:36 ERROR ProfitTrailerService - openOrders - 
nl.komtek.pt.utils.j: No value was returned
at nl.komtek.pt.services.ProfitTrailerService.f(ProfitTrailerService.java:962) ~[classes!/:2.0.13]
at nl.komtek.pt.services.ProfitTrailerService.getOpenOrdersScheduled(ProfitTrailerService.java:576) [classes!/:2.0.13]
at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke() [classes!/:2.0.13]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:342) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:405) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:324) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$b4dd9e7f.getOpenOrdersScheduled() [classes!/:2.0.13]
at nl.komtek.pt.schedules.DefaultScheduledTasks.b(DefaultScheduledTasks.java:66) [classes!/:2.0.13]
at nl.komtek.pt.schedules.DefaultScheduledTasks.fetchData(DefaultScheduledTasks.java:52) [classes!/:2.0.13]
at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
2018-07-01 04:08:56 ERROR ProfitTrailerService - Error occured in chartData, message No value was returned, result: 
2018-07-01 04:08:56 ERROR ProfitTrailerService - Error occured in ticker, message No value was returned, result: 
2018-07-01 04:09:21 INFO ProfitTrailerService - Cache Heartbeat
2018-07-01 04:09:57 INFO Application - PT Version: 2.0.13
2018-07-01 04:09:57 INFO Application - Java Version: 1.8.0_171
2018-07-01 04:10:06 INFO Application$a - Server initialized with port: 8081
2018-07-01 04:10:12 INFO ProfitTrailerService - PAIRS Heartbeat
2018-07-01 04:10:12 INFO ProfitTrailerService - DCA Heartbeat
2018-07-01 04:10:13 INFO ProfitTrailerService - Cache Heartbeat
