### ISSUE TITLE
GainStrategyRun Error

### ISSUE THREAD

**Issue by MKFZ8** [taniman/profit-trailer#642]
I'm receiving the following error after trying to restart the bot several times. Any help is appreciated.

INFO: Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-01-11 15:49:37 INFO ProfitTrailerService - Normal Heartbeat
2018-01-11 15:49:37 INFO ProfitTrailerService - DCA Heartbeat
2018-01-11 15:49:39 INFO ProfitTrailerService - Cache Heartbeat
2018-01-11 15:52:42 ERROR GainStrategyRunner - An error occured
nl.komtek.pt.utils.PTHandledErrorException: ERROR: -1013, Filter failure: MIN_NOTIONAL
        at nl.komtek.pt.services.ProfitTrailerService.analyzeResult(ProfitTrailerService.java:859) ~[classes!/:1.2.6.7]
        at nl.komtek.pt.services.ProfitTrailerService.lambda$normalSellOrder$20(ProfitTrailerService.java:805) ~[classes!/:1.2.6.7]
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
        at nl.komtek.pt.services.ProfitTrailerService.normalSellOrder(ProfitTrailerService.java:805) ~[classes!/:1.2.6.7]
        at nl.komtek.pt.services.ProfitTrailerService.sellOrder(ProfitTrailerService.java:768) ~[classes!/:1.2.6.7]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.7]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$17f1bad6.sellOrder(<generated>) ~[classes!/:1.2.6.7]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.gainSell(GainStrategyRunner.java:153) ~[classes!/:1.2.6.7]
        at nl.komtek.pt.strategyrunner.GainStrategyRunner.checkSellStrategy(GainStrategyRunner.java:93) [classes!/:1.2.6.7]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by YoJeff** [comment]
Not a bug.
https://wiki.profittrailer.io/doku.php/common_errors#error1013_filter_failuremin_notional

**Comment by MKFZ8** [comment]
Thanks for sharing. The issue was I hadn't updated my BTC_dust settings. If anyone else is having this issue here's a link to the configuration.properties#dust section.
https://wiki.profittrailer.io/doku.php/configuration.properties#dust
