### ISSUE TITLE
Error messages with new version

### ISSUE THREAD

**Issue by DaNiSeL** [taniman/profit-trailer#823]
Hello,

Since i am using the new version i am getting alot of error messages.

ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 5
ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 11
BinanceWebSocketAdapter24Ticker - onWebSocketError: CONTINUATION frame without prior !FIN
BinanceWebSocketAdapter24Ticker - Error in websocket message Expected a com.google.gson.JsonArray but was com.google.gson.JsonObject
inanceWebSocketAdapter24Ticker - Error in websocket message com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 55224 path $[143].F:
WARN BinanceWSTicker - Unhandled Error (closing connection)
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Unknown Source) ~[?:1.8.0_151]
	at java.lang.StringBuffer.toString(Unknown Source) ~[?:1.8.0_151]
	at java.io.StringWriter.toString(Unknown Source) ~[?:1.8.0_151]
	at com.google.gson.JsonElement.toString(JsonElement.java:325) ~[gson-2.8.0.jar!/:?]
	at nl.komtek.pt.client.generic.BinanceWSTicker.onMessage(BinanceWSTicker.java:24) ~[x-client-1.2.7.jar!/:?]
	at com.webcerebrium.binance.websocket.BinanceWebSocketAdapter24Ticker.onWebSocketText(BinanceWebSocketAdapter24Ticker.java:29) ~[binance-api-1.0.8.jar!/:?]
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) ~[websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) ~[websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) ~[websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:375) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [websocket-common-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:278) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:148) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [jetty-util-9.4.5.v20170502.jar!/:9.4.5.v20170502]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
2018-01-25 07:48:49 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Java heap space

Etc etc......

**Comment by YoJeff** [comment]
The binance issues are known and widely reported.
