### ISSUE TITLE
Java Error Vers. 14. on Binance

### ISSUE THREAD

**Issue by xyr0x** [taniman/profit-trailer#923]
2018-01-31 07:58:40 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_151]
	at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$9109bf07.e(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:53) ~[classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by cristianserban** [comment]
hi. 
can you please provide the entire log ?

**Comment by xyr0x** [comment]
The entire log...


2018-01-31 07:41:00 INFO Util - Detected configuration changes
2018-01-31 07:41:01 INFO ProfitTrailerService - Normal Heartbeat
2018-01-31 07:41:01 INFO ProfitTrailerService - DCA Heartbeat
2018-01-31 07:41:03 INFO ProfitTrailerService - Cache Heartbeat
2018-01-31 07:41:14 ERROR GenericStrategyRunner - An error occured
2018-01-31 07:41:18 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:23 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:28 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:33 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:38 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:43 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:41:48 INFO DCAStrategyRunner - You are not allowed to buy LENDBTC. Buy will exceed min buy balance 0.04396939. BAL: 0,01762938 - AVGC: 0.03243375
2018-01-31 07:41:48 ERROR DCAStrategyRunner - An error occured
2018-01-31 07:43:49 INFO Util - Detected configuration changes
2018-01-31 07:43:54 INFO Util - Detected configuration changes
2018-01-31 07:43:59 INFO Util - Detected configuration changes
2018-01-31 07:46:53 INFO DCAStrategyRunner - You are not allowed to buy STRATBTC. Buy will exceed min buy balance 0.04396939. BAL: 0,01762938 - AVGC: 0.01620612
2018-01-31 07:51:05 INFO ProfitTrailerService - Normal Heartbeat
2018-01-31 07:51:06 INFO ProfitTrailerService - Cache Heartbeat
2018-01-31 07:51:27 INFO ProfitTrailerService - DCA Heartbeat
2018-01-31 07:51:47 INFO Util - Detected configuration changes
2018-01-31 07:51:52 INFO Util - Detected configuration changes
2018-01-31 07:51:57 INFO DCAStrategyRunner - You are not allowed to buy STRATBTC. Buy will exceed min buy balance 0.05084318. BAL: 0,01762938 - AVGC: 0.01620612
2018-01-31 07:51:57 INFO Util - Detected configuration changes
2018-01-31 07:56:58 INFO DCAStrategyRunner - You are not allowed to buy STRATBTC. Buy will exceed min buy balance 0.04396939. BAL: 0,01762938 - AVGC: 0.01620612
2018-01-31 07:58:40 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_151]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_151]
	at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$9109bf07.e(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:53) ~[classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by cristianserban** [comment]
please check your configs 
it seems you updated a config and after the you got the errors 

what modifs did you made?

**Comment by xyr0x** [comment]
I Use the Profit Trailer Feeder, that updates the config automatically. With VErs. 12, 11 or 10 i get no error.

**Comment by cristianserban** [comment]
please do the following:
1. stop both bot and feeder
2. remove confs from bot trading folder
3. start feeder and when you that it wrote the confs into trading folder of pt that start bot.

let me know if you still got thoes..
also please activate debug in bot:
add this inside application.properties before you start the bot
logging.level.nl.komtek = DEBUG

**Comment by taniman** [comment]
We are aware of this error and as long as the ticker prices are updated you can ignore this error
