### ISSUE TITLE
IndexOutOfBoundsException in log

### ISSUE THREAD

**Issue by merricrubiyat** [taniman/profit-trailer#934]
```2018-01-31 11:22:04 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
        at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$35d4bdac.e(<generated>) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:53) ~[classes!/:1.2.6.14]```

**Comment by smoochy** [comment]
I am having the same issue this moring. Running version .14 on windows server 2016. also having PTF running.

It came up, but aparrently the bot kept on working, as prices updated on the web gui afterwards.

migth this be related to the java scheduler check in the background?
![indexoob](https://user-images.githubusercontent.com/34371932/35664002-661869a2-0720-11e8-8d31-e3c8506dd9d6.jpg)

**Comment by cristianserban** [comment]
ignore
