### ISSUE TITLE
The completeBalances Cache is not alive (STATUS_SHUTDOWN)

### ISSUE THREAD

**Issue by Frankdd** [taniman/profit-trailer#944]
Version 2.14 with Binance (also after reïnstalling the entire package)

2018-02-01 15:20:05 INFO Util - Detected configuration changes
2018-02-01 15:20:05 INFO ProfitTrailerService - Normal Heartbeat
2018-02-01 15:20:06 INFO ProfitTrailerService - DCA Heartbeat
2018-02-01 15:20:06 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: The completeBalances Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:74) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e003866a.getCompleteBalances(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getTotaltradingPairs(StrategyRunnerHelper.java:979) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:61) ~[classes!/:1.2.6.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-02-01 15:20:06 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: The completeBalances Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4075) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2766) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.Cache.get(Cache.java:1727) ~[ehcache-2.9.0.jar!/:2.9.0]
	at org.springframework.cache.ehcache.EhCacheCache.lookup(EhCacheCache.java:142) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.ehcache.EhCacheCache.get(EhCacheCache.java:74) ~[spring-context-support-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:364) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e003866a.getCompleteBalances(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.bot.strategy.helper.StrategyRunnerHelper.getTotaltradingPairs(StrategyRunnerHelper.java:979) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:72) ~[classes!/:1.2.6.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-02-01 15:20:08 ERROR ProfitTrailerService - Occured in ticker, handled result exception The CacheManager has been shut down. It can no longer be used.
2018-02-01 15:20:08 INFO ProfitTrailerService - Seems like the exchange is spitting out invalid data. Let's wait 5 minutes and see
2018-02-01 15:20:08 ERROR AllScheduledTasks - The ticker Cache is not alive (STATUS_SHUTDOWN)
2018-02-01 15:20:08 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: The CacheManager has been shut down. It can no longer be used.
	at net.sf.ehcache.CacheManager.checkStatus(CacheManager.java:1619) ~[ehcache-2.9.0.jar!/:2.9.0]
	at net.sf.ehcache.CacheManager.getCache(CacheManager.java:1155) ~[ehcache-2.9.0.jar!/:2.9.0]
	at nl.komtek.pt.schedules.AllScheduledTasks.fetchData(AllScheduledTasks.java:52) ~[classes!/:1.2.6.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-02-01 15:20:09 ERROR ProfitTrailerService - Occured in ticker, handled result exception The CacheManager has been shut down. It can no longer be used.

**Comment by YoJeff** [comment]
unless I am missing something -- you shut down the bot.

**Comment by Frankdd** [comment]
Got it when booting. Running ok however

**Comment by BrotherMunk** [comment]
I am having the exact same issue. Changed the java 8 from update 151 to 161 and still having the same issue.
