### ISSUE TITLE
ERROR DCAStrategyRunner - An error occured

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#952]
Please help. Bot was working fine until tonight
![image](https://user-images.githubusercontent.com/69228/35722577-c3fadaba-07ab-11e8-942d-fc1b929a5b6d.png)

I tried: 
- restarting the bot
- changing max_buy to 5 with only 5 buy triggers
Still the same error

**Here are my DCA settings**
max_cost = 0.025
max_buy_times = 7
max_buy_spread = 1
min_buy_balance = 0
min_buy_volume = 500

buy_value = 0
buy_trigger = -5
buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -5.5
buy_trigger_2 = -7
buy_trigger_3 = -9
buy_trigger_4 = -11
buy_trigger_5 = -13
buy_trigger_6 = -15
buy_trigger_7 = -17

trailing_profit = 0.1
trailing_buy = 0.5
sell_strategy = GAIN
sell_value = .77
sell_trigger = .77

stop_loss_trigger = 0
stop_loss_timeout = 0

buy_available_volume_trigger = 125
ignore_sell_only_mode = true
pending_order_wait_time = 0

**Comment by taniman** [comment]
in application.properties add logging.level.nl.komtek = DEBUG
save the file and restart the bot.

With this new log file, contact support as this place is not for debugging problems

**Comment by a7777777v** [comment]
@taniman The error was fixed by changing the setting min_buy_balance = 0 to min_buy_balance = 0.05

However I have a 0.246 BTC balance, doesn't make sense?

As soon as I changed to 0.05 it made the buy

```
2018-02-02 00:42:54 DEBUG DCAStrategyRunner - An error occured
nl.komtek.pt.utils.b: ERROR: -2010, Account has insufficient balance for requested action.
	at nl.komtek.pt.services.ProfitTrailerService.d(ProfitTrailerService.java:898) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:845) ~[classes!/:1.2.6.14]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.b(ProfitTrailerService.java:845) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:808) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$45d4bdac.a(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:206) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:139) [classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```
