### ISSUE TITLE
Bug: 1.2.6.14 - Index out of bounds exception

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer#957]
I am getting the following error, every 4-6 hours:

2018-02-01 22:04:14 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
        at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e003866a.e(<generated>) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:53) ~[classes!/:1.2.6.14]
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by 4Ykw** [comment]
I am having the same. I have increased java limits to check if something changes:
java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx1024m -Xms1024m

**Comment by 4Ykw** [comment]
6 hours without a reboot with 1GB of heap size.

**Comment by Gitulu** [comment]
I got the same error on Win 10. Maybe this is related with ticket #847

**Comment by YoJeff** [comment]
The binance update issues are known, reducing clutter here.
