### ISSUE TITLE
[FIX] Setting min_buy_balance=0 produces unclear errors.

### ISSUE THREAD

**Issue by a7777777v** [taniman/profit-trailer#961]
**Error:** ERROR DCAStrategyRunner - An error occured
![image](https://user-images.githubusercontent.com/69228/35746649-551fb29a-07fc-11e8-8ae2-8dbcfc7568a7.png)

**Fix:** change the setting **min_buy_balance = 0** to **min_buy_balance = 0.05** (or above 0)

I have 0.246 BTC balance when getting the below error, and right after changing to 0.05 it made a buy with no more errors

**Debug/Error Log**
```
2018-02-02 00:42:54 DEBUG DCAStrategyRunner - An error occured
nl.komtek.pt.utils.b: ERROR: -2010, Account has insufficient balance for requested action.
	at nl.komtek.pt.services.ProfitTrailerService.d(ProfitTrailerService.java:898) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:845) ~[classes!/:1.2.6.14]
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145) ~[failsafe-1.0.4.jar!/:1.0.4]
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56) ~[failsafe-1.0.4.jar!/:1.0.4]
	at nl.komtek.pt.services.ProfitTrailerService.b(ProfitTrailerService.java:845) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService.a(ProfitTrailerService.java:808) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$45d4bdac.a(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.a(DCAStrategyRunner.java:206) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:139) [classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```
First reported in #952

**Comment by YoJeff** [comment]
This isn't a forum.  It's for bugs only, your comment on the other thread is noted.

**Comment by a7777777v** [comment]
@YoJeff This is a Bug in the min_buy_balance calculation.  needs to be reopened. 0 is a valid entry.

**Comment by YoJeff** [comment]
Not according to the wiki, but the error should be clearer.
