### ISSUE TITLE
1.2.6.14 ERROR - Unexpected error occurred in scheduled task

### ISSUE THREAD

**Issue by mayday79** [taniman/profit-trailer#963]
I currently get the following Error in my Logs that occurs every 24h:

2018-02-02 19:16:47 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$48f48e27.e(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:56) ~[classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

Release is the 1.2.6.14

Is there anything I can do?

**Comment by taniman** [comment]
ignore it. will be fixed in next release
