### ISSUE TITLE
[BUG] v1.2.6.14 - PT ignores min buy balance at times and starts buying.

### ISSUE THREAD

**Issue by neo302** [taniman/profit-trailer#981]
This has now happened two times.  PT behaves properly for a while.  You can see in the console it will say it can't buy because it will exceed min buy balance.  I'm using min balance as a percentage and it is set to 50.  Then at some point, something messes up and it will buy.  The first time it happened it got me into 3 or 4 new positions.  When I went to restart, there was this error below.  I understand it will show some errors due to the fact I'm restarting, I just want to show you what I have:

![image](https://user-images.githubusercontent.com/17410338/35767358-040f7f76-08b9-11e8-8060-51a26802835d.png)

I've restarted multiple times since then.  It just happened again and when restarting, I got this error. 

![image](https://user-images.githubusercontent.com/17410338/35767388-5e719616-08b9-11e8-8d10-6a3accae2c6f.png)

My balance has not gotten close to being able to buy again.

**Comment by BiergartentwinTR** [comment]
I have the same issue:
2018-02-03 20:16:06 ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_162]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_162]
        at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$e6f48e27.e(<generated>) ~[classes!/:1.2.6.14]
        at nl.komtek.pt.strategyrunner.NormalStrategyRunner.checkBuyStrategy(NormalStrategyRunner.java:56) ~[classes!/:1.2.6.14]
        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

**Comment by YoJeff** [comment]
Garbage in, garbage out rules always apply in computing.  If binance returns wrong (or no) information, the decisions made downstream are tainted.

Retry with .15.
